import { Megaphone, Save, Settings, ShieldAlert } from 'lucide-react'
import { DashboardShell } from '@/components/DashboardShell'
import { SubmitButton } from '@/components/ui/SubmitButton'
import { requireAdmin } from '@/lib/auth'
import { adminUpdateSiteSettingsAction } from '@/lib/actions'

export default async function AdminSite(){
 const {supabase}=await requireAdmin();const {data:row}=await supabase.from('site_settings').select('value,updated_at').eq('key','platform').maybeSingle();const v:any=row?.value||{}
 return <DashboardShell admin><div className="page-head internal-page-head"><div><div className="kicker">ADMIN / SITE SETTINGS</div><h1>Configurações da plataforma</h1><p>Ajuste mensagens e CTAs operacionais sem editar o código.</p></div><span className="pill"><Settings size={13}/> PLATFORM</span></div><div className="site-settings-grid"><form action={adminUpdateSiteSettingsAction} className="card"><div className="panel-head"><div><span className="section-index">PUBLIC EXPERIENCE</span><h2>Conteúdo global</h2></div><Save size={18}/></div><div className="field"><label><Megaphone size={13}/> Aviso global</label><input name="announcement" maxLength={180} defaultValue={v.announcement||''} placeholder="Ex.: CTF nacional abre inscrições em breve"/></div><div className="two-col"><div className="field"><label>E-mail de suporte</label><input name="support_email" type="email" defaultValue={v.support_email||'contato@fortifysec.com.br'}/></div><div className="field"><label>Label de prêmio CTF</label><input name="ctf_prize_label" defaultValue={v.ctf_prize_label||'R$ 15.000'}/></div><div className="field"><label>CTA Academy</label><input name="academy_cta" defaultValue={v.academy_cta||'Explorar Academy'}/></div><div className="field"><label>CTA Labs</label><input name="labs_cta" defaultValue={v.labs_cta||'Abrir Cyber Range'}/></div></div><div className="field"><label>Modo da plataforma</label><select name="maintenance_mode" defaultValue={String(!!v.maintenance_mode)}><option value="false">Operação normal</option><option value="true">Manutenção</option></select></div><SubmitButton idleLabel="SALVAR CONFIGURAÇÕES" pendingLabel="SALVANDO..."/></form><aside className="card settings-security"><ShieldAlert size={28}/><span className="section-index">OPERATION NOTE</span><h3>Configurações sensíveis</h3><p>Credenciais do Supabase, Mercado Pago e provedor de Labs continuam nas variáveis de ambiente do Vercel. Esta página controla somente conteúdo e estado operacional do produto.</p><div className="settings-meta"><span>Última atualização</span><strong>{row?.updated_at?new Date(row.updated_at).toLocaleString('pt-BR'):'—'}</strong></div></aside></div></DashboardShell>
}
