import Link from 'next/link'
import { notFound } from 'next/navigation'
import { replySupportTicketAdminAction, updateSupportTicketAction } from '@/app/admin/actions'
import { PortalHeader } from '@/components/PortalHeader'
import { StatusPill } from '@/components/StatusPill'
import { getAdminTicketDetail } from '@/lib/admin-data'

function meta(status:string){const map:Record<string,{label:string,tone:'green'|'warning'|'danger'|'cyan'}>={open:{label:'ABERTO',tone:'cyan'},in_progress:{label:'EM ATENDIMENTO',tone:'warning'},waiting_customer:{label:'AGUARDANDO CLIENTE',tone:'warning'},resolved:{label:'RESOLVIDO',tone:'green'},closed:{label:'FECHADO',tone:'green'}};return map[status]??{label:String(status).toUpperCase(),tone:'cyan' as const}}

export default async function Page({params,searchParams}:{params:Promise<{id:string}>,searchParams:Promise<Record<string,string|undefined>>}){
  const {id}=await params;const q=await searchParams;const data=await getAdminTicketDetail(id);if(!data)notFound();const {ticket,organization,messages}=data;const st=meta(ticket.status)
  return <><PortalHeader kicker="ADMIN / SERVICE DESK / TICKET" title={ticket.subject} copy={`${organization?.name??'Cliente'} · #${String(ticket.id).slice(0,8)} · aberto em ${new Date(ticket.created_at).toLocaleString('pt-BR')}`} action={<StatusPill tone={st.tone}>{st.label}</StatusPill>}/>{q.updated&&<div className="form-success">Status do chamado atualizado.</div>}{q.sent&&<div className="form-success">Resposta enviada ao cliente.</div>}{q.error&&<div className="form-error">Não foi possível concluir: {q.error}.</div>}
    <div className="ticket-detail-grid"><section className="portal-card"><div className="card-head"><div><span className="section-index">CLIENTE</span><h2>{organization?.name??'Organização'}</h2></div><StatusPill tone={ticket.priority==='critical'?'danger':ticket.priority==='high'?'warning':'cyan'}>{ticket.priority}</StatusPill></div><div className="ticket-meta-grid"><span><small>Categoria</small><strong>{ticket.category||'support'}</strong></span><span><small>Status</small><strong>{st.label}</strong></span><span><small>Atualizado</small><strong>{new Date(ticket.updated_at).toLocaleString('pt-BR')}</strong></span><span><small>Última resposta</small><strong>{ticket.last_reply_at?new Date(ticket.last_reply_at).toLocaleString('pt-BR'):'—'}</strong></span></div><Link className="text-link" href={`/admin/clientes/${ticket.organization_id}`}>ABRIR CLIENTE →</Link></section><section className="portal-card"><span className="section-index">SOLICITAÇÃO ORIGINAL</span><h2>Descrição</h2><p className="ticket-description">{ticket.description}</p></section></div>

    <div className="admin-ticket-workspace"><section className="portal-card ticket-conversation"><div className="card-head"><h2>Conversa com o cliente</h2><span className="section-index">{messages.length} RESPOSTAS</span></div><div className="ticket-thread"><article className="ticket-message customer"><div><strong>CLIENTE</strong><span>{new Date(ticket.created_at).toLocaleString('pt-BR')}</span></div><p>{ticket.description}</p></article>{messages.filter((m:any)=>!m.is_internal).map((m:any)=><article className={`ticket-message ${m.author_role==='staff'?'staff':'customer'}`} key={m.id}><div><strong>{m.author_role==='staff'?'FORTIFY OPS':'CLIENTE'}</strong><span>{new Date(m.created_at).toLocaleString('pt-BR')}</span></div><p>{m.body}</p></article>)}</div>
      {ticket.status!=='closed'&&<form className="ticket-reply-form" action={replySupportTicketAdminAction}><input type="hidden" name="ticket_id" value={ticket.id}/><input type="hidden" name="organization_id" value={ticket.organization_id}/><label>Responder ao cliente<textarea name="body" required rows={5} placeholder="Explique a ação realizada, peça uma validação ou informe o próximo passo."/></label><label>Após enviar<select name="next_status" defaultValue="waiting_customer"><option value="in_progress">Manter em atendimento</option><option value="waiting_customer">Aguardar cliente</option><option value="resolved">Marcar como resolvido</option></select></label><button className="btn" type="submit">ENVIAR RESPOSTA →</button></form>}</section>

      <section className="portal-card ticket-ops-panel"><span className="section-index">STATUS / RESOLUÇÃO</span><h2>Atualizar atendimento</h2><form className="compact-form" action={updateSupportTicketAction}><input type="hidden" name="ticket_id" value={ticket.id}/><input type="hidden" name="organization_id" value={ticket.organization_id}/><label>Status<select name="status" defaultValue={ticket.status}><option value="open">Aberto</option><option value="in_progress">Em atendimento</option><option value="waiting_customer">Aguardando cliente</option><option value="resolved">Resolvido</option><option value="closed">Fechado</option></select></label><label>Nota de resolução<textarea name="resolution_note" rows={6} defaultValue={ticket.resolution_note??''} placeholder="Descreva o que foi corrigido, restaurado ou validado. Esta informação fica visível para o cliente."/></label><button className="btn full" type="submit">SALVAR STATUS</button></form>{ticket.resolved_at&&<div className="resolution-box"><span className="section-index">RESOLVIDO EM</span><strong>{new Date(ticket.resolved_at).toLocaleString('pt-BR')}</strong></div>}</section></div>
    <Link className="text-link" href="/admin/chamados">← VOLTAR PARA FILA</Link>
  </>
}
