import { ShieldCheck, UserCog, UsersRound } from 'lucide-react'
import { DashboardShell } from '@/components/DashboardShell'
import { SubmitButton } from '@/components/ui/SubmitButton'
import { requireAdmin } from '@/lib/auth'
import { adminSetUserRoleAction, adminToggleUserAction } from '@/app/actions'

export default async function AdminUsers(){
 const {supabase,user}=await requireAdmin();const {data:users}=await supabase.from('profiles').select('id,name,email,role,blocked,xp,created_at').order('created_at',{ascending:false})
 const admins=(users||[]).filter((u:any)=>u.role==='admin').length;const blocked=(users||[]).filter((u:any)=>u.blocked).length
 return <DashboardShell admin><div className="page-head internal-page-head"><div><div className="kicker">ADMIN / ACCESS CONTROL</div><h1>Usuários</h1><p>Gerencie papéis, status de conta e acesso administrativo.</p></div><div className="head-stats"><span className="pill active"><UsersRound size={13}/>{users?.length||0} CONTAS</span><span className="pill"><ShieldCheck size={13}/>{admins} ADMINS</span><span className="pill locked">{blocked} BLOQUEADAS</span></div></div><div className="tablewrap"><table><thead><tr><th>Usuário</th><th>E-mail</th><th>Role</th><th>XP</th><th>Status</th><th>Criado</th><th>Ações</th></tr></thead><tbody>{(users||[]).map((u:any)=><tr key={u.id}><td><strong>{u.name}</strong></td><td>{u.email}</td><td><span className={`pill ${u.role==='admin'?'active':''}`}>{u.role}</span></td><td><span className="xp-score">{u.xp} XP</span></td><td><span className={`pill ${u.blocked?'danger':'active'}`}>{u.blocked?'Bloqueado':'Ativo'}</span></td><td>{new Date(u.created_at).toLocaleDateString('pt-BR')}</td><td>{u.id===user.id?<span className="muted">Conta atual</span>:<div className="row-actions"><form action={adminToggleUserAction}><input type="hidden" name="user_id" value={u.id}/><input type="hidden" name="blocked" value={String(u.blocked)}/><SubmitButton className={u.blocked?'btn small':'btn danger small'} idleLabel={u.blocked?'DESBLOQUEAR':'BLOQUEAR'} pendingLabel="ATUALIZANDO..."/></form><form action={adminSetUserRoleAction}><input type="hidden" name="user_id" value={u.id}/><input type="hidden" name="role" value={u.role==='admin'?'student':'admin'}/><SubmitButton className="btn secondary small" idleLabel={u.role==='admin'?'REMOVER ADMIN':'TORNAR ADMIN'} pendingLabel="ATUALIZANDO..."/></form></div>}</td></tr>)}</tbody></table></div></DashboardShell>
}
