import { Building2, CheckCircle2, Clock3 } from 'lucide-react'
import { DashboardShell } from '@/components/DashboardShell'
import { SubmitButton } from '@/components/ui/SubmitButton'
import { requireAdmin } from '@/lib/auth'
import { adminVerifyCompanyAction } from '@/app/actions'

export default async function AdminCompanies(){
 const {supabase}=await requireAdmin();const {data:companies}=await supabase.from('companies').select('id,name,slug,website,location,verified,active,created_at,company_members(user_id,member_role,profiles(name,email)),jobs(id,status)').order('created_at',{ascending:false})
 return <DashboardShell admin><div className="page-head internal-page-head"><div><div className="kicker">ADMIN / EMPLOYER NETWORK</div><h1>Empresas</h1><p>Valide empresas antes de permitir a publicação de vagas.</p></div><span className="pill active"><Building2 size={13}/>{companies?.length||0} EMPRESAS</span></div><section className="admin-resource-grid">{(companies||[]).map((c:any)=>{const owner=(c.company_members||[]).find((m:any)=>m.member_role==='owner')||c.company_members?.[0];const profile=Array.isArray(owner?.profiles)?owner.profiles[0]:owner?.profiles;return <article className="card admin-resource-card" key={c.id}><div className="panel-head"><span className={`pill ${c.verified?'active':'locked'}`}>{c.verified?<><CheckCircle2 size={11}/> VALIDADA</>:<><Clock3 size={11}/> PENDENTE</>}</span><Building2 size={18}/></div><h3>{c.name}</h3><p>{c.location||'Localização não informada'}</p><div className="meta-row"><span>{profile?.name||'Responsável'}</span><span>{profile?.email||'—'}</span><span>{c.jobs?.length||0} VAGAS</span></div>{c.website&&<a className="btn secondary small" href={c.website} target="_blank" rel="noreferrer">ABRIR SITE</a>}<form action={adminVerifyCompanyAction}><input type="hidden" name="company_id" value={c.id}/><input type="hidden" name="verified" value={String(c.verified)}/><SubmitButton className="btn" idleLabel={c.verified?'REMOVER VALIDAÇÃO':'VALIDAR EMPRESA'} pendingLabel="ATUALIZANDO..."/></form></article>})}</section>{!companies?.length&&<div className="empty-state">Nenhuma empresa cadastrada.</div>}</DashboardShell>
}
