import Link from 'next/link'
import { Activity, KeyRound, LockKeyhole, ShieldCheck, TerminalSquare } from 'lucide-react'
import { adminLoginAction } from '@/app/actions'
import { SubmitButton } from '@/components/ui/SubmitButton'

export default async function AdminLogin({searchParams}:{searchParams:Promise<{erro?:string}>}){
 const p=await searchParams
 return <main className="admin-auth-page"><div className="admin-auth-shell"><section className="admin-auth-visual"><div className="admin-auth-brand"><span className="brand-mark">F</span><div><strong>FORTIFYSEC</strong><small>CONTROL CENTER</small></div></div><div className="admin-auth-copy"><span className="section-index">ADMINISTRATIVE GATEWAY</span><h1>Controle total.<br/><em>Acesso restrito.</em></h1><p>Gerencie Academy, Labs, Challenges, CTF, usuários, pagamentos e conteúdo em um único centro operacional.</p></div><div className="admin-terminal"><div className="terminal-head"><span className="terminal-dot"/><span className="terminal-dot"/><span className="terminal-dot"/> root@fortifysec:~</div><div className="terminal-body"><div><span className="terminal-green">$</span> fortifyctl status</div><div>[<span className="terminal-green">+</span>] academy ........ online</div><div>[<span className="terminal-green">+</span>] cyber-range .... online</div><div>[<span className="terminal-green">+</span>] control-center . secured</div><br/><div className="terminal-cyan">AUTHORIZATION REQUIRED</div></div></div><div className="admin-trust-row"><span><ShieldCheck size={14}/> Role verificada</span><span><Activity size={14}/> Sessão auditável</span><span><KeyRound size={14}/> Acesso restrito</span></div></section><section className="admin-auth-form-panel"><div className="admin-login-card"><div className="admin-login-icon"><LockKeyhole size={22}/></div><span className="section-index">CONTROL CENTER LOGIN</span><h2>Acesso administrativo</h2><p className="muted">Entre com uma conta autorizada para administrar a plataforma.</p>{p.erro&&<p className="error">{p.erro}</p>}<form action={adminLoginAction}><div className="field"><label>E-mail administrativo</label><input required type="email" name="email" autoComplete="email" placeholder="admin@fortifysec.com.br"/></div><div className="field"><label>Senha</label><input required type="password" name="password" autoComplete="current-password" placeholder="••••••••"/></div><SubmitButton className="btn full-btn admin-login-btn" idleLabel="ACESSAR CONTROL CENTER →" pendingLabel="VALIDANDO ACESSO..."/></form><div className="admin-login-foot"><TerminalSquare size={13}/><span>Somente contas com permissão administrativa.</span></div><Link className="back-platform-link" href="/login">← Voltar ao login da plataforma</Link></div></section></div></main>
}
