import Link from 'next/link'
import { Boxes, BriefcaseBusiness, Flag, GraduationCap, ShieldCheck, Swords } from 'lucide-react'
export default function Home(){return <>
<main>
<section className="hero"><div className="container hero-grid"><div><div className="kicker">OFFENSIVE SECURITY PLATFORM</div><h1>APRENDA.<br/><em>HACKEIE.</em><br/>PROVE.</h1><p className="hero-copy">Uma plataforma brasileira para transformar estudo em habilidade comprovada. Academy, laboratórios, desafios, CTF, ranking e perfil técnico em um único cyber range.</p><div className="hero-actions"><Link className="btn" href="/cadastro">CRIAR CONTA →</Link><Link className="btn secondary" href="/login">ACESSAR PLATAFORMA</Link></div></div><div className="terminal-card"><div className="terminal-head"><span className="terminal-dot"/><span className="terminal-dot"/><span className="terminal-dot"/> fortify@range:~</div><div className="terminal-body"><div><span className="terminal-green">fortify@labs</span>:<span className="terminal-cyan">~</span>$ ./start-career.sh</div><br/><div>[<span className="terminal-green">+</span>] carregando trilha: <span className="terminal-white">cybersecurity</span></div><div>[<span className="terminal-green">+</span>] academy ............. ready</div><div>[<span className="terminal-green">+</span>] labs ................ ready</div><div>[<span className="terminal-green">+</span>] challenges .......... ready</div><div>[<span className="terminal-green">+</span>] ctf/ranking ......... ready</div><br/><div className="terminal-green">ACCESS GRANTED — prove what you know.</div></div></div></div></section>
<section className="metrics-row"><div className="metric"><strong>600+</strong><span>horas de formação</span></div><div className="metric"><strong>37+</strong><span>especializações</span></div><div className="metric"><strong>100%</strong><span>orientado à prática</span></div><div className="metric"><strong>R$ 15K</strong><span>CTF principal</span></div></section>
<section className="section" id="academy"><div className="container"><div className="section-head"><div><div className="kicker">01 / ACADEMY</div><h2>Conhecimento que termina em execução.</h2></div><p className="section-copy">Cursos e trilhas organizados para preparar o aluno para o laboratório. O conteúdo é liberado somente com matrícula ativa, com progresso e XP gravados no servidor.</p></div><div className="feature-grid"><article className="feature-card" data-index="01"><div className="feature-icon"><GraduationCap size={20}/></div><h3>Academy</h3><p className="muted">Aulas, módulos, progresso e trilhas técnicas com acesso controlado por matrícula.</p></article><article className="feature-card" data-index="02"><div className="feature-icon"><Boxes size={20}/></div><h3>Cyber Labs</h3><p className="muted">Ambientes controlados para transformar conteúdo em prática e evidência técnica.</p></article><article className="feature-card" data-index="03"><div className="feature-icon"><Swords size={20}/></div><h3>Challenges</h3><p className="muted">Flags validadas no backend, XP por resolução e dificuldade progressiva.</p></article></div></div></section>
<section className="section alt" id="labs"><div className="container"><div className="section-head"><div><div className="kicker">02 / CYBER RANGE</div><h2>Entre no laboratório.</h2></div><p className="section-copy">O backend valida conta, matrícula e sessão antes de revelar qualquer conexão do laboratório.</p></div><div className="cta-panel"><div><span className="tag green">SERVER VERIFIED ACCESS</span><h2>Um painel. Toda a jornada.</h2><p className="muted">Aprenda na Academy, execute no Lab, resolva o Challenge, some XP e suba no ranking.</p></div><div className="terminal-body"><div>&gt; status.auth <span className="terminal-green">VERIFIED</span></div><div>&gt; enrollment <span className="terminal-green">ACTIVE</span></div><div>&gt; lab.session <span className="terminal-cyan">READY</span></div></div></div></div></section>
<section className="section" id="ctf"><div className="container"><div className="section-head"><div><div className="kicker">03 / COMPETE</div><h2>Desempenho vira reputação.</h2></div><p className="section-copy">Ranking, CTF e perfil público opcional criam uma ponte entre quem sabe fazer e empresas que procuram talento técnico.</p></div><div className="feature-grid"><article className="feature-card" data-index="04"><div className="feature-icon"><Flag size={20}/></div><h3>CTF</h3><p className="muted">Competições, pontuação e classificação em tempo real a partir das resoluções.</p></article><article className="feature-card" data-index="05"><div className="feature-icon"><ShieldCheck size={20}/></div><h3>Proof of Skill</h3><p className="muted">XP e histórico técnico sustentados por ações realizadas dentro da plataforma.</p></article><article className="feature-card" data-index="06"><div className="feature-icon"><BriefcaseBusiness size={20}/></div><h3>Talent Network</h3><p className="muted">O aluno escolhe se quer aparecer para empresas e exibir headline, XP e posição.</p></article></div></div></section>
<section className="section alt"><div className="container cta-panel"><div><div className="kicker">READY?</div><h2>Seu próximo nível começa no range.</h2><p className="muted">Crie sua conta. O conteúdo premium continua protegido até a confirmação da matrícula.</p></div><div className="hero-actions"><Link className="btn" href="/cadastro">COMEÇAR AGORA</Link><Link className="btn secondary" href="/talentos">VER TALENTOS</Link></div></div></section>
</main><footer className="footer"><div className="container footer-inner"><span>© 2026 FortifySec.</span><span className="mono">LEARN // HACK // PROVE</span></div></footer></>}
