import Link from 'next/link'
import { notFound } from 'next/navigation'
import { BriefcaseBusiness, Building2, CheckCircle2, MapPin, ShieldCheck } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'
import { applyToJobAction } from '@/app/actions'
import { SubmitButton } from '@/components/ui/SubmitButton'

export default async function JobDetail({params,searchParams}:{params:Promise<{slug:string}>,searchParams:Promise<{aplicado?:string}>}){
 const {slug}=await params;const q=await searchParams;const supabase=await createClient();const [{data:job},{data:{user}}]=await Promise.all([supabase.from('jobs').select('id,title,slug,description,requirements,location,work_mode,employment_type,seniority,salary_min,salary_max,published_at,companies(id,name,description,website,location,verified)').eq('slug',slug).eq('status','published').maybeSingle(),supabase.auth.getUser()]);if(!job)notFound();const company=Array.isArray((job as any).companies)?(job as any).companies[0]:(job as any).companies;let applied=false;if(user){const {data:a}=await supabase.from('job_applications').select('id').eq('job_id',job.id).eq('user_id',user.id).maybeSingle();applied=Boolean(a)}
 return <main><section className="section"><div className="container"><div className="page-head"><div><div className="kicker">{company?.name} / VAGA</div><h1>{job.title}</h1><p>{job.location||company?.location||'Brasil'} · {job.work_mode} · {job.employment_type.replace('_',' ')}</p></div><span className="pill active"><ShieldCheck size={13}/> EMPRESA VERIFICADA</span></div>{q.aplicado&&<div className="alert success-alert"><CheckCircle2 size={16}/> Candidatura enviada para {company?.name}.</div>}<div className="content-grid"><section><article className="card"><span className="section-index">SOBRE A VAGA</span><p style={{whiteSpace:'pre-wrap'}}>{job.description}</p></article><article className="card" style={{marginTop:18}}><span className="section-index">REQUISITOS</span><p style={{whiteSpace:'pre-wrap'}}>{job.requirements||'Requisitos serão alinhados durante o processo seletivo.'}</p></article></section><aside><div className="card"><div className="panel-head"><div><span className="section-index">OPORTUNIDADE</span><h3>Detalhes</h3></div><BriefcaseBusiness size={18}/></div><div className="target-row"><span><MapPin size={14}/> LOCAL</span><strong>{job.location||'A combinar'}</strong></div><div className="target-row"><span>MODELO</span><strong>{job.work_mode.toUpperCase()}</strong></div><div className="target-row"><span>NÍVEL</span><strong>{job.seniority||'ABERTO'}</strong></div>{job.salary_min&&<div className="target-row"><span>FAIXA</span><strong>R$ {Number(job.salary_min).toLocaleString('pt-BR')}{job.salary_max?` — ${Number(job.salary_max).toLocaleString('pt-BR')}`:''}</strong></div>}</div><div className="card" style={{marginTop:18}}><div className="panel-head"><div><span className="section-index">APLICAÇÃO</span><h3>Candidatar-se</h3></div></div>{!user?<><p className="muted">Entre na sua conta FortifySec para enviar seu perfil técnico.</p><Link className="btn full-btn" href="/login">ENTRAR PARA CANDIDATAR →</Link></>:applied?<div className="pwned-state"><CheckCircle2 size={34}/><strong>CANDIDATURA ENVIADA</strong><p>A empresa já recebeu seu perfil.</p></div>:<form action={applyToJobAction}><input type="hidden" name="job_id" value={job.id}/><input type="hidden" name="slug" value={job.slug}/><div className="field"><label>Mensagem para a empresa (opcional)</label><textarea name="cover_note" rows={5} placeholder="Conte brevemente por que esta vaga combina com você."/></div><SubmitButton className="btn full-btn" idleLabel="ENVIAR CANDIDATURA →" pendingLabel="ENVIANDO..."/></form>}</div><div className="card" style={{marginTop:18}}><div className="panel-head"><div><span className="section-index">EMPRESA</span><h3>{company?.name}</h3></div><Building2 size={18}/></div><p className="muted">{company?.description||'Empresa participante da Talent Network FortifySec.'}</p>{company?.website&&<a className="btn secondary small" href={company.website} target="_blank" rel="noreferrer">SITE DA EMPRESA</a>}</div></aside></div></div></section></main>
}
