import Link from 'next/link'
import { Binary, BookOpenCheck, Bot, Boxes, CheckCircle2, CloudCog, Code2, Cpu, GraduationCap, Network, ShieldCheck, Smartphone, Swords, TerminalSquare, Wifi, Zap } from 'lucide-react'

const tracks=[
 {code:'01',title:'Fundamentos & Base Técnica',hours:108,icon:TerminalSquare,courses:['Introdução à FortifySec','Fundamentos de Segurança da Informação e Pentest','Dominando o Linux e Shell para Pentesters','Introdução ao Python e Algoritmos','Fundamentos de Criptografia e Senhas','Python Orientado a Objetos e Automação','Fundamentos de Redes para Pentesters','Docker para Pentesters']},
 {code:'02',title:'Infraestrutura & Redes',hours:112,icon:Network,courses:['Dominando o Recon em Pentest','Dominando o Pentest em Infraestrutura de Redes','Ataque em Redes Wi-Fi','Segurança em Redes Wi-Fi','Ataques Denial of Service (DoS) e Botnets','Ataques Man-in-the-Middle (MITM)','Metodologias de Pentest na Prática']},
 {code:'03',title:'Web, Cloud & Bug Bounty',hours:108,icon:CloudCog,courses:['Desenvolvimento Web para Pentesters','Ataque em Aplicações Web','Pentest em Ambientes em Nuvem (Cloud Pentesting)','Automação e Estratégias em Bug Bounty','Inteligência Artificial para Pentest Web','LLM Hacking: Exploração de IAs']},
 {code:'04',title:'Mobile, Engenharia Social & Privacidade',hours:72,icon:Smartphone,courses:['Pentest em Aplicativos Android','Desenvolvimento de Malwares para Android','Técnicas de Phishing e Engenharia Social','Fundamentos de Privacidade e Anonimato']},
 {code:'05',title:'Exploit Dev, Malware & Active Directory',hours:137,icon:Binary,courses:['Fundamentos de C para Pentesters','Fundamentos de PowerShell para Pentesters','Pós-exploração Linux','Pós-exploração Windows e Pentest em Active Directory','Assembly para Pentesters e Desenvolvimento de Exploits','Análise e Desenvolvimento de Malwares','Técnicas de Evasão de Antivírus e EDR']},
 {code:'06',title:'Hardware Hacking & Red Team',hours:96,icon:Cpu,courses:['Fundamentos de Eletrônica','Gadgets para Pentest e Red Team','Exploração de Jogos com Hardware (Game Cheat)','Hardware Hacking na Prática','Hackeando Chips: Side-Channel Analysis e Fault Injection']},
]

export function AcademyPublic(){
 return <main>
  <section className="hero compact-hero academy-hero"><div className="container academy-hero-grid"><div><div className="kicker">FORTIFYSEC / ACADEMY</div><h1>ESTUDE.<br/><em>PRATIQUE.</em><br/>EVOLUA.</h1><p className="hero-copy">Uma formação progressiva em segurança ofensiva, do fundamento ao avançado, conectada diretamente a Labs, Challenges, CTF e evolução por XP.</p><div className="hero-actions"><Link className="btn" href="/planos">VER PLANOS →</Link><Link className="btn secondary" href="/cadastro">COMEÇAR GRÁTIS</Link></div></div><div className="academy-summary-card"><span className="section-index">FORMAÇÃO COMPLETA</span><strong>633h</strong><small>de conteúdo técnico</small><div className="academy-summary-grid"><div><b>37</b><span>cursos</span></div><div><b>06</b><span>trilhas</span></div><div><b>100%</b><span>online</span></div><div><b>XP</b><span>progressão</span></div></div></div></div></section>
  <section className="academy-metrics"><div className="container academy-metric-grid"><div><GraduationCap size={18}/><strong>37 cursos</strong><span>do zero ao avançado</span></div><div><BookOpenCheck size={18}/><strong>633 horas</strong><span>de formação estruturada</span></div><div><Boxes size={18}/><strong>Cyber Labs</strong><span>prática integrada</span></div><div><Swords size={18}/><strong>Challenges & CTF</strong><span>prove sua habilidade</span></div></div></section>
  <section className="section"><div className="container"><div className="section-head"><div><div className="kicker">FORMAÇÃO / ROADMAP</div><h2>Uma trilha completa para segurança ofensiva.</h2></div><p className="section-copy">Comece pelos fundamentos, avance por redes e aplicações, aprofunde exploração e pós-exploração e chegue a temas avançados de malware, hardware, IA e Red Team.</p></div><div className="academy-benefit-grid"><article className="academy-benefit"><ShieldCheck size={20}/><h3>Progressão estruturada</h3><p>Conteúdo organizado para construir base técnica antes de avançar para cenários mais complexos.</p></article><article className="academy-benefit"><Zap size={20}/><h3>XP e evolução</h3><p>Seu progresso acompanha a jornada e conecta Academy, Labs, Challenges e Ranking.</p></article><article className="academy-benefit"><Bot size={20}/><h3>Conteúdo atual</h3><p>Web, Cloud, IA, Active Directory, malware, hardware e técnicas modernas de ofensiva.</p></article></div></div></section>
  <section className="section alt curriculum-section"><div className="container"><div className="section-head curriculum-head"><div><div className="kicker">GRADE CURRICULAR</div><h2>37 cursos. 633 horas.</h2></div><p className="section-copy">Uma grade ampla para construir repertório técnico e transformar conhecimento em execução.</p></div><div className="curriculum-grid">{tracks.map(track=>{const Icon=track.icon;return <article className="curriculum-track" key={track.code}><div className="curriculum-track-head"><div className="track-icon"><Icon size={19}/></div><div><span className="section-index">TRILHA {track.code}</span><h3>{track.title}</h3></div><div className="track-hours"><strong>{track.hours}h</strong><span>{track.courses.length} cursos</span></div></div><ol className="curriculum-list">{track.courses.map((course,index)=><li key={course}><span>{String(index+1).padStart(2,'0')}</span><b>{course}</b><CheckCircle2 size={14}/></li>)}</ol></article>})}</div></div></section>
  <section className="section"><div className="container academy-path"><div><span className="section-index">ACADEMY → CYBER RANGE</span><h2>Aprenda. Execute. Prove.</h2><p>Leve o conteúdo da aula para ambientes práticos, resolva missões e construa um histórico técnico visível no seu perfil.</p></div><div className="academy-path-flow"><span><Code2 size={17}/> ACADEMY</span><i>→</i><span><Boxes size={17}/> LABS</span><i>→</i><span><Swords size={17}/> CHALLENGES</span><i>→</i><span><Wifi size={17}/> CTF</span></div><div className="hero-actions"><Link className="btn" href="/planos">CONHECER PLANOS →</Link><Link className="btn secondary" href="/labs">EXPLORAR LABS</Link></div></div></section>
 </main>
}
