import Link from 'next/link'
import { notFound } from 'next/navigation'
import { PortalHeader } from '@/components/PortalHeader'
import { StatusPill } from '@/components/StatusPill'
import { getAdminReportDetail } from '@/lib/admin-data'

export default async function Page({params}:{params:Promise<{id:string}>}){
  const {id}=await params;const data=await getAdminReportDetail(id);if(!data)notFound();const {report,organization}=data;const summary=(report.summary??{}) as Record<string,any>;const health=Number(report.health_score??0)
  return <><PortalHeader kicker="ADMIN / REPORTS / DETAIL" title={`${organization?.name??'Cliente'} · ${new Date(`${report.reference_month}T12:00:00`).toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}`} copy="Indicadores consolidados do relatório mensal e origem dos dados." action={<StatusPill tone={health>=90?'green':health>=70?'warning':'danger'}>{health.toFixed(0)}% HEALTH</StatusPill>}/>
    <section className="portal-metrics report-detail-metrics"><article><span>HEALTH</span><strong>{health.toFixed(0)}%</strong><small>indicador consolidado</small></article><article><span>BACKUP SUCCESS</span><strong>{Number(report.backup_success_rate??0).toFixed(1)}%</strong><small>{summary.backup_jobs_success??0} / {summary.backup_jobs_total??0} jobs</small></article><article><span>RECOVERY TESTS</span><strong>{report.recovery_tests_passed??0}</strong><small>aprovados no mês</small></article><article><span>INCIDENTES</span><strong>{report.incidents_count??0}</strong><small>{summary.incidents_open??0} abertos</small></article></section>
    <div className="report-detail-grid"><section className="portal-card"><span className="section-index">ORIGEM</span><h2>{report.source==='client'?'Gerado pelo cliente':'Fortify Ops'}</h2><div className="ticket-meta-grid"><span><small>Gerado em</small><strong>{report.generated_at?new Date(report.generated_at).toLocaleString('pt-BR'):new Date(report.created_at).toLocaleString('pt-BR')}</strong></span><span><small>Status</small><strong>{report.generation_status??'ready'}</strong></span><span><small>Provider</small><strong>{organization?.provider??'Fortify'}</strong></span><span><small>Plano</small><strong>{organization?.plan??'—'}</strong></span></div></section><section className="portal-card"><span className="section-index">COBERTURA</span><h2>Dados usados</h2><div className="ticket-meta-grid"><span><small>Ativos protegidos</small><strong>{summary.assets_protected??0} / {summary.assets_total??0}</strong></span><span><small>Jobs OK</small><strong>{summary.backup_jobs_success??0} / {summary.backup_jobs_total??0}</strong></span><span><small>Recovery tests</small><strong>{summary.recovery_tests_passed??report.recovery_tests_passed??0}</strong></span><span><small>Incidentes abertos</small><strong>{summary.incidents_open??0}</strong></span></div></section></div>
    <section className="portal-card"><div className="card-head"><div><span className="section-index">METODOLOGIA</span><h2>Health transparente</h2></div><StatusPill tone="cyan">50 / 40 / 10</StatusPill></div><div className="report-formula"><span>Ativos protegidos × 50%</span><span>Sucesso de backup × 40%</span><span>Higiene de incidentes × 10%</span></div><p>{summary.formula||'Relatório criado pela operação Fortify.'}</p>{report.report_url&&<a className="btn secondary" href={report.report_url} target="_blank" rel="noreferrer">ABRIR ARQUIVO PUBLICADO</a>}</section>
    <div style={{display:'flex',gap:18,flexWrap:'wrap'}}><Link className="text-link" href="/admin/relatorios">← VOLTAR PARA RELATÓRIOS</Link><Link className="text-link" href={`/admin/clientes/${report.organization_id}`}>ABRIR CLIENTE →</Link></div>
  </>
}
