import { notFound, redirect } from 'next/navigation'
import { DashboardShell } from '@/components/DashboardShell'
import { requireUser } from '@/lib/auth'
import { completeLessonAction } from './server-actions'

function youtubeEmbed(url:string){try{const u=new URL(url);if(u.hostname.includes('youtube.com')){const v=u.searchParams.get('v');return v?`https://www.youtube.com/embed/${encodeURIComponent(v)}`:null}if(u.hostname==='youtu.be'){const v=u.pathname.replace('/','');return v?`https://www.youtube.com/embed/${encodeURIComponent(v)}`:null}}catch{}return null}

export default async function Course({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params;const {supabase,user}=await requireUser()
 const {data:course}=await supabase.from('courses').select('id,title,description').eq('slug',slug).eq('published',true).maybeSingle();if(!course)notFound()
 const {data:enrollment}=await supabase.from('enrollments').select('id,status').eq('user_id',user.id).eq('course_id',course.id).eq('status','active').maybeSingle();if(!enrollment)redirect('/painel/cursos?bloqueado=1')
 const [{data:lessons},{data:progress},{data:profile}]=await Promise.all([supabase.from('lessons').select('id,title,position,video_url,content,xp_reward').eq('course_id',course.id).order('position'),supabase.from('lesson_progress').select('lesson_id,completed').eq('user_id',user.id),supabase.from('profiles').select('role').eq('id',user.id).single()]);const done=new Set((progress||[]).filter((p:any)=>p.completed).map((p:any)=>p.lesson_id));const total=lessons?.length||0;const pct=total?Math.round(done.size/total*100):0
 return <DashboardShell admin={profile?.role==='admin'}><div className="page-head"><div><div className="kicker">ACADEMY / COURSE</div><h1>{course.title}</h1><p>{course.description}</p></div><span className="pill active">{pct}% COMPLETE</span></div><div className="progress" style={{marginBottom:22}}><span style={{width:`${pct}%`}}/></div>{(lessons||[]).map((l:any)=>{const embed=l.video_url?youtubeEmbed(l.video_url):null;return <article className="lesson" key={l.id}><div className="topline"><div><span className="tag">LESSON {String(l.position).padStart(2,'0')}</span><h3>{l.title}</h3>{l.content&&<p className="muted" style={{lineHeight:1.7,whiteSpace:'pre-wrap'}}>{l.content}</p>}</div>{done.has(l.id)?<span className="pill active">CONCLUÍDA</span>:<form action={completeLessonAction}><input type="hidden" name="lesson_id" value={l.id}/><input type="hidden" name="course_id" value={course.id}/><input type="hidden" name="slug" value={slug}/><button className="btn secondary">CONCLUIR · +{l.xp_reward||0} XP</button></form>}</div>{embed&&<div className="video-frame"><iframe src={embed} title={l.title} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen/></div>}{l.video_url&&!embed&&<a className="btn secondary" href={l.video_url} target="_blank" rel="noreferrer">ABRIR CONTEÚDO EXTERNO →</a>}</article>})}{!lessons?.length&&<div className="empty-state">Este curso ainda não possui aulas publicadas.</div>}</DashboardShell>
}
