import { UsersRound } from 'lucide-react'
import { CompanyShell } from '@/components/CompanyShell'
import { requireCompany } from '@/lib/auth'
import { companyUpdateApplicationStatusAction } from '@/app/actions'
import { SubmitButton } from '@/components/ui/SubmitButton'

export default async function CompanyCandidates(){
 const {supabase,company}=await requireCompany();const {data:apps}=await supabase.from('job_applications').select('id,status,cover_note,created_at,jobs!inner(id,title,company_id),profiles(id,name,email,headline,xp,github_url,linkedin_url,open_to_work)').eq('jobs.company_id',company.id).order('created_at',{ascending:false})
 return <CompanyShell companyName={company.name}><div className="page-head internal-page-head"><div><div className="kicker">EMPLOYER / CANDIDATES</div><h1>Candidatos</h1><p>Veja o perfil e o XP dos operadores que se candidataram às suas vagas.</p></div><span className="pill active"><UsersRound size={13}/>{apps?.length||0} CANDIDATOS</span></div><div className="challenge-grid">{(apps||[]).map((a:any)=>{const p=Array.isArray(a.profiles)?a.profiles[0]:a.profiles;const job=Array.isArray(a.jobs)?a.jobs[0]:a.jobs;return <article className="challenge-card" key={a.id}><div className="challenge-top"/><div className="challenge-body"><span className="section-index">{job?.title}</span><h3>{p?.name}</h3><p className="muted">{p?.headline||p?.email}</p><div className="meta-row"><span>{p?.xp||0} XP</span><span>{String(a.status).toUpperCase()}</span></div>{a.cover_note&&<p>{a.cover_note}</p>}<div className="hero-actions">{p?.github_url&&<a className="btn secondary small" href={p.github_url} target="_blank" rel="noreferrer">GITHUB</a>}{p?.linkedin_url&&<a className="btn secondary small" href={p.linkedin_url} target="_blank" rel="noreferrer">LINKEDIN</a>}</div><form action={companyUpdateApplicationStatusAction}><input type="hidden" name="application_id" value={a.id}/><select name="status" defaultValue={a.status}><option value="submitted">Recebida</option><option value="viewed">Visualizada</option><option value="interview">Entrevista</option><option value="rejected">Recusada</option><option value="hired">Contratada</option></select><SubmitButton className="btn secondary" idleLabel="ATUALIZAR" pendingLabel="SALVANDO..."/></form></div></article>})}</div>{!apps?.length&&<div className="empty-state">Nenhuma candidatura recebida ainda.</div>}</CompanyShell>
}
