import { PublicCta } from '@/components/PublicCta'
const phases=[
 {n:'01',tag:'ASSESSMENT',title:'Diagnóstico e criticidade',items:['Inventário de dados e sistemas','Classificação por criticidade','RPO/RTO desejados','Riscos e dependências','Estimativa de volume e crescimento']},
 {n:'02',tag:'DESIGN',title:'Arquitetura de proteção',items:['Política 3-2-1/variações quando aplicável','Retenção por tipo de dado','Destino secundário e isolamento','Criptografia e credenciais','Procedimentos de contingência']},
 {n:'03',tag:'DEPLOY',title:'Implantação e baseline',items:['Conexão das fontes','Agendamento dos jobs','Alertas e monitoramento','Teste inicial de restauração','Documentação do ambiente']},
 {n:'04',tag:'OPERATE',title:'Operação contínua',items:['Acompanhamento de falhas','Tratamento de alertas','Relatório mensal','Revisão de capacidade','Gestão de mudanças']},
 {n:'05',tag:'RECOVER',title:'Teste e recuperação',items:['Testes periódicos','Evidências do restore','Medição de tempo real','Runbook atualizado','Apoio em incidente real']},
]
export default function ComoFunciona(){return <main><section className="page-hero"><div className="container"><div className="kicker">FORTIFY CLOUD / MÉTODO</div><h1>Proteção é processo. Não só armazenamento.</h1><p>O ciclo Fortify transforma backup em uma capacidade operacional de recuperação, com responsabilidade clara e evidências periódicas.</p></div></section><section className="section"><div className="container timeline">{phases.map(p=><article key={p.n}><div className="timeline-num">{p.n}</div><div><span className="section-index">{p.tag}</span><h2>{p.title}</h2></div><div className="timeline-items">{p.items.map(x=><span key={x}>{x}</span>)}</div></article>)}</div></section><section className="section alt"><div className="container"><div className="section-head"><div><div className="kicker">RESPONSABILIDADE COMPARTILHADA</div><h2>Fortify gerencia. O cliente mantém governança.</h2></div><p className="section-copy">A matriz de responsabilidade entra no onboarding para deixar claro quem aprova retenção, acessos, janelas, restaurações e mudanças.</p></div><div className="responsibility-grid"><article><strong>FORTIFY CLOUD</strong><span>Configuração e monitoramento</span><span>Tratamento de alertas</span><span>Testes e relatórios</span><span>Apoio à recuperação</span></article><article><strong>CLIENTE</strong><span>Dono do dado e prioridades</span><span>Aprovação de políticas</span><span>Acessos necessários</span><span>Validação do negócio</span></article></div></div></section><PublicCta/></main>}
