import { BookOpenCheck, Film, ListOrdered, PlusCircle, Sparkles, Zap } from 'lucide-react'
import { DashboardShell } from '@/components/DashboardShell'
import { SubmitButton } from '@/components/ui/SubmitButton'
import { requireAdmin } from '@/lib/auth'
import { adminCreateLessonAction } from '@/app/actions'

export default async function AdminLessons({searchParams}:{searchParams:Promise<{criada?:string,erro?:string}>}){
 const query=await searchParams;const {supabase}=await requireAdmin();const [{data:courses},{data:lessons}]=await Promise.all([
  supabase.from('courses').select('id,title,slug').order('title'),
  supabase.from('lessons').select('id,title,position,xp_reward,video_url,course_id,courses(title,slug)').order('course_id').order('position')
 ])
 return <DashboardShell admin>
   <div className="page-head internal-page-head"><div><div className="kicker">ADMIN / CONTENT STUDIO</div><h1>Postagem de aulas</h1><p>Publique conteúdo, vídeo e XP dentro de uma trilha. O acesso permanece protegido pela matrícula.</p></div><div className="head-stats"><span className="pill active"><BookOpenCheck size={13}/>{(lessons||[]).length} AULAS</span><span className="pill"><Sparkles size={13}/> CONTENT STUDIO</span></div></div>
   {query.criada&&<div className="alert success-alert">Aula publicada com sucesso.</div>}{query.erro&&<div className="alert danger-alert">Não foi possível publicar a aula. Confira curso, posição e dados informados.</div>}
   <div className="admin-studio-grid"><form action={adminCreateLessonAction} className="card content-studio"><div className="studio-header"><div><span className="section-index">NEW LESSON</span><h2>Criar nova aula</h2><p>Organize título, vídeo, conteúdo e recompensa.</p></div><PlusCircle size={27}/></div><div className="two-col"><div className="field"><label>Curso / trilha</label><select name="course_id" required><option value="">Selecione o curso</option>{(courses||[]).map((c:any)=><option key={c.id} value={c.id}>{c.title}</option>)}</select></div><div className="field"><label>Título da aula</label><input name="title" required placeholder="Ex.: Reconhecimento e enumeração"/></div><div className="field"><label><ListOrdered size={12}/> Posição</label><input name="position" type="number" min="1" defaultValue="1"/></div><div className="field"><label><Zap size={12}/> XP da aula</label><input name="xp_reward" type="number" min="0" defaultValue="10"/></div></div><div className="field"><label><Film size={12}/> URL do vídeo / YouTube / streaming</label><input name="video_url" placeholder="https://youtube.com/watch?v=..."/></div><div className="field"><label>Conteúdo / instruções</label><textarea name="content" rows={11} placeholder={'Introdução\n\nObjetivos da aula...\n\nPasso a passo...'} /></div><div className="studio-footer"><div className="studio-security"><span className="status-dot"/>A aula só será lida por aluno com matrícula ativa.</div><SubmitButton idleLabel="PUBLICAR AULA →" pendingLabel="PUBLICANDO AULA..."/></div></form><aside className="card studio-guide"><span className="section-index">PUBLISHING GUIDE</span><h3>Padrão FortifySec</h3><div className="guide-step"><strong>01</strong><div><b>Título objetivo</b><span>Use nomes que indiquem claramente a competência da aula.</span></div></div><div className="guide-step"><strong>02</strong><div><b>Conteúdo executável</b><span>Inclua objetivo, contexto e passos que levem à prática.</span></div></div><div className="guide-step"><strong>03</strong><div><b>Vídeo externo seguro</b><span>HTTPS/YouTube é validado antes de ser persistido.</span></div></div><div className="guide-step"><strong>04</strong><div><b>XP proporcional</b><span>A recompensa é creditada uma única vez na conclusão.</span></div></div></aside></div>
   <section className="card lesson-library"><div className="panel-head"><div><span className="section-index">CONTENT LIBRARY</span><h3>Aulas publicadas</h3></div><span className="mono tiny-label">{(courses||[]).length} CURSOS</span></div><div className="tablewrap"><table><thead><tr><th>Curso</th><th>#</th><th>Aula</th><th>Mídia</th><th>XP</th></tr></thead><tbody>{(lessons||[]).map((l:any)=><tr key={l.id}><td><strong>{l.courses?.title||'—'}</strong></td><td className="rank">{String(l.position).padStart(2,'0')}</td><td>{l.title}</td><td>{l.video_url?<span className="pill active"><Film size={11}/> VÍDEO</span>:<span className="pill">TEXTO</span>}</td><td><span className="xp-score">+{l.xp_reward} XP</span></td></tr>)}</tbody></table></div></section>
 </DashboardShell>
}
