import Link from 'next/link'
import { BookOpenCheck, Film, Layers3, PlusCircle, Zap } from 'lucide-react'
import { DashboardShell } from '@/components/DashboardShell'
import { SubmitButton } from '@/components/ui/SubmitButton'
import { requireAdmin } from '@/lib/auth'
import { adminCreateLessonAction, adminToggleLessonAction } from '@/lib/actions'

export default async function AdminLessons({searchParams}:{searchParams:Promise<{criada?:string,erro?:string}>}){
 const query=await searchParams;const {supabase}=await requireAdmin();const [{data:courses},{data:modules},{data:lessons}]=await Promise.all([
  supabase.from('courses').select('id,title,slug').order('title'),
  supabase.from('course_modules').select('id,course_id,title,position').order('course_id').order('position'),
  supabase.from('lessons').select('id,title,summary,position,xp_reward,video_url,published,course_id,module_id,courses(title,slug)').order('course_id').order('position')
 ])
 const moduleMap=new Map((modules||[]).map((m:any)=>[m.id,m]))
 return <DashboardShell admin>
  <div className="page-head internal-page-head"><div><div className="kicker">ADMIN / CONTENT LIBRARY</div><h1>Biblioteca de aulas</h1><p>Publique uma aula rapidamente ou abra o Studio do curso para trabalhar a grade completa.</p></div><div className="hero-actions"><span className="pill active"><BookOpenCheck size={13}/>{(lessons||[]).length} AULAS</span><Link className="btn secondary" href="/admin/cursos"><Layers3 size={14}/> STUDIOS DE CURSO</Link></div></div>
  {query.criada&&<div className="alert success-alert">Aula publicada com sucesso.</div>}{query.erro&&<div className="alert danger-alert">Não foi possível publicar a aula.</div>}
  <div className="admin-studio-grid"><form action={adminCreateLessonAction} className="card content-studio"><div className="studio-header"><div><span className="section-index">QUICK PUBLISH</span><h2>Nova aula</h2><p>Escolha curso, módulo e conteúdo.</p></div><PlusCircle size={27}/></div><input type="hidden" name="return_to" value="/admin/aulas"/><div className="two-col"><div className="field"><label>Curso</label><select name="course_id" required><option value="">Selecione</option>{(courses||[]).map((c:any)=><option key={c.id} value={c.id}>{c.title}</option>)}</select></div><div className="field"><label>Módulo</label><select name="module_id"><option value="">Sem módulo</option>{(modules||[]).map((m:any)=><option key={m.id} value={m.id}>{m.title}</option>)}</select></div><div className="field"><label>Título</label><input name="title" required/></div><div className="field"><label>Posição</label><input name="position" type="number" min="1" defaultValue="1"/></div><div className="field"><label><Zap size={12}/> XP</label><input name="xp_reward" type="number" min="0" defaultValue="10"/></div><div className="field"><label>Status</label><select name="published" defaultValue="true"><option value="true">Publicada</option><option value="false">Rascunho</option></select></div></div><div className="field"><label>Resumo</label><input name="summary"/></div><div className="field"><label><Film size={12}/> URL do vídeo</label><input name="video_url"/></div><div className="field"><label>Conteúdo</label><textarea name="content" rows={9}/></div><SubmitButton idleLabel="PUBLICAR AULA →" pendingLabel="PUBLICANDO AULA..."/></form><aside className="card studio-guide"><span className="section-index">WORKFLOW</span><h3>Fluxo recomendado</h3><div className="guide-step"><strong>01</strong><div><b>Crie o curso</b><span>Defina nome, descrição, preço e status.</span></div></div><div className="guide-step"><strong>02</strong><div><b>Abra o Course Studio</b><span>Crie módulos e organize a sequência.</span></div></div><div className="guide-step"><strong>03</strong><div><b>Publique as aulas</b><span>Associe cada aula ao módulo correto.</span></div></div><div className="guide-step"><strong>04</strong><div><b>Revise a experiência</b><span>Abra o curso antes de anunciar a trilha.</span></div></div></aside></div>
  <section className="card lesson-library"><div className="panel-head"><div><span className="section-index">ALL CONTENT</span><h3>Aulas da plataforma</h3></div><span className="mono tiny-label">{(courses||[]).length} CURSOS</span></div><div className="tablewrap"><table><thead><tr><th>Curso</th><th>Módulo</th><th>#</th><th>Aula</th><th>Mídia</th><th>XP</th><th>Status</th><th>Ação</th></tr></thead><tbody>{(lessons||[]).map((l:any)=><tr key={l.id}><td><Link href={`/admin/cursos/${l.course_id}`}><strong>{l.courses?.title||'—'}</strong></Link></td><td>{moduleMap.get(l.module_id)?.title||'—'}</td><td className="rank">{String(l.position).padStart(2,'0')}</td><td>{l.title}</td><td>{l.video_url?<span className="pill active"><Film size={11}/> VÍDEO</span>:<span className="pill">TEXTO</span>}</td><td><span className="xp-score">+{l.xp_reward}</span></td><td><span className={`pill ${l.published?'active':'locked'}`}>{l.published?'PUBLICADA':'RASCUNHO'}</span></td><td><form action={adminToggleLessonAction}><input type="hidden" name="lesson_id" value={l.id}/><input type="hidden" name="published" value={String(l.published)}/><input type="hidden" name="return_to" value="/admin/aulas"/><SubmitButton className="btn secondary small" idleLabel={l.published?'OCULTAR':'PUBLICAR'} pendingLabel="..."/></form></td></tr>)}</tbody></table></div></section>
 </DashboardShell>
}
