import { provisionOnboardingAction, updateOnboardingStatusAction } from '@/app/admin/actions'
import { PortalHeader } from '@/components/PortalHeader'
import { StatusPill } from '@/components/StatusPill'
import { getAdminOnboarding } from '@/lib/admin-data'

function tone(status: string) { return status === 'provisioned' ? 'green' : status === 'needs_info' ? 'warning' : status === 'rejected' ? 'danger' : 'cyan' as const }

export default async function Page({ searchParams }: { searchParams: Promise<{ error?: string; updated?: string }> }) {
  const q = await searchParams
  const rows = await getAdminOnboarding()
  return <><PortalHeader kicker="ADMIN / ONBOARDING" title="Solicitações de provisionamento" copy="Da conta criada até a organização pronta para receber backups."/>{q.error && <div className="form-error">Não foi possível concluir a operação ({q.error}).</div>}{q.updated && <div className="form-success">Solicitação atualizada.</div>}<div className="onboarding-admin-grid">{rows.length ? rows.map((r: any) => <article className="portal-card onboarding-admin-card" key={r.id}><div className="card-head"><div><span className="section-index">{r.email || 'USUÁRIO'}</span><h2>{r.organization_name}</h2></div><StatusPill tone={tone(r.status)}>{r.status}</StatusPill></div><div className="admin-request-meta"><span><small>Plano</small><strong>{r.plan}</strong></span><span><small>Volume</small><strong>{r.data_volume || '—'}</strong></span><span><small>Contato</small><strong>{r.contact_name}</strong></span><span><small>Atualizado</small><strong>{new Date(r.updated_at).toLocaleDateString('pt-BR')}</strong></span></div>{r.infrastructure && <p><strong>Infra:</strong> {r.infrastructure}</p>}{r.critical_systems && <p><strong>Críticos:</strong> {r.critical_systems}</p>}{r.admin_notes && <div className="admin-note"><strong>Nota atual</strong><p>{r.admin_notes}</p></div>}{r.status !== 'provisioned' && <div className="admin-request-actions"><form action={provisionOnboardingAction}><input type="hidden" name="id" value={r.id}/><button className="btn" type="submit">PROVISIONAR →</button></form><form className="inline-review-form" action={updateOnboardingStatusAction}><input type="hidden" name="id" value={r.id}/><select name="status" defaultValue="reviewing"><option value="reviewing">Em análise</option><option value="needs_info">Pedir informações</option><option value="rejected">Rejeitar / ajustar</option></select><input name="admin_notes" placeholder="Mensagem para o cliente"/><button className="btn secondary" type="submit">ATUALIZAR</button></form></div>}</article>) : <div className="empty-state"><StatusPill tone="green">ZERO PENDÊNCIAS</StatusPill><h2>Nenhum onboarding aguardando análise.</h2></div>}</div></>
}
