-- FortifySec V10 SAFE ADDITIVE — Cyber Range hardening
-- Apply after the current production migrations.
-- This migration changes no CSS, layouts, React components or existing routes.
-- It is intentionally compatible with databases where the previous V9 migration
-- was executed and later the application code was reverted.

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- 1) CTF anti-cheat + dynamic per-session flag, transparently reusing the
--    existing submit_ctf_flag(event_uuid, challenge_uuid, candidate_flag) RPC.
-- ---------------------------------------------------------------------------
alter table public.challenges
  add column if not exists dynamic_flag_enabled boolean not null default false;

alter table public.ctf_events
  add column if not exists freeze_at timestamptz,
  add column if not exists max_attempts_per_minute integer not null default 10;

alter table public.ctf_events
  drop constraint if exists ctf_events_attempt_rate_check;
alter table public.ctf_events
  add constraint ctf_events_attempt_rate_check
  check (max_attempts_per_minute between 3 and 120);

create table if not exists public.ctf_flag_attempts (
  id bigint generated by default as identity primary key,
  event_id uuid not null references public.ctf_events(id) on delete cascade,
  challenge_id uuid not null references public.challenges(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  success boolean not null default false,
  attempted_at timestamptz not null default now()
);
create index if not exists ctf_flag_attempts_rate_idx
  on public.ctf_flag_attempts(user_id,event_id,challenge_id,attempted_at desc);

-- Private config is never exposed to anon/authenticated. The SQL editor/service
-- role can read it once to configure the Range Provider with the same secret.
create table if not exists public.range_private_config (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);
insert into public.range_private_config(key,value)
values ('dynamic_flag_secret', encode(gen_random_bytes(32),'hex'))
on conflict(key) do nothing;

alter table public.range_private_config enable row level security;
revoke all on public.range_private_config from public,anon,authenticated;

-- Hardened flag submit. Lab-backed dynamic challenges use:
-- FORTIFY{HMAC_SHA256(session_id:user_id:provider_lab_key)[0..31]}
-- If a provider is not configured yet, the function safely falls back to the
-- static challenge flag instead of breaking an existing CTF.
create or replace function public.submit_ctf_flag(
  event_uuid uuid,
  challenge_uuid uuid,
  candidate_flag text
) returns boolean
language plpgsql
security definer
set search_path=public
as $$
declare
  v_static_hash bytea;
  v_reward integer;
  v_event_points integer;
  v_dynamic_enabled boolean;
  v_lab_id uuid;
  v_provider_lab_key text;
  v_provider_session_id text;
  v_secret text;
  v_dynamic_flag text;
  v_attempt_limit integer;
  v_recent_attempts integer;
  v_valid boolean := false;
  v_inserted_event integer := 0;
  v_inserted_global integer := 0;
begin
  if auth.uid() is null or not public.has_platform_access() then return false; end if;

  select e.max_attempts_per_minute
    into v_attempt_limit
    from public.ctf_events e
   where e.id=event_uuid
     and e.status='live'
     and now() between e.starts_at and e.ends_at;
  if v_attempt_limit is null then return false; end if;

  if not exists(
    select 1 from public.ctf_participants p
    where p.event_id=event_uuid and p.user_id=auth.uid()
  ) then return false; end if;

  select count(*)::integer
    into v_recent_attempts
    from public.ctf_flag_attempts a
   where a.user_id=auth.uid()
     and a.event_id=event_uuid
     and a.challenge_id=challenge_uuid
     and a.attempted_at > now() - interval '1 minute';
  if v_recent_attempts >= coalesce(v_attempt_limit,10) then return false; end if;

  select c.flag_hash,
         c.xp_reward,
         c.dynamic_flag_enabled,
         c.lab_id,
         coalesce(l.provider_lab_id, l.id::text),
         coalesce(ec.points_override,c.xp_reward)
    into v_static_hash,
         v_reward,
         v_dynamic_enabled,
         v_lab_id,
         v_provider_lab_key,
         v_event_points
    from public.ctf_event_challenges ec
    join public.challenges c on c.id=ec.challenge_id
    left join public.labs l on l.id=c.lab_id
   where ec.event_id=event_uuid
     and ec.challenge_id=challenge_uuid
     and c.published=true;

  if v_static_hash is null then return false; end if;

  -- Dynamic validation only activates when the Challenge explicitly enables it
  -- AND there is a live provider-backed session. This makes rollout reversible.
  if coalesce(v_dynamic_enabled,false) and v_lab_id is not null then
    select s.provider_session_id
      into v_provider_session_id
      from public.lab_sessions s
     where s.user_id=auth.uid()
       and s.lab_id=v_lab_id
       and s.status='running'
       and s.expires_at > now()
       and nullif(s.provider_session_id,'') is not null
     order by s.started_at desc
     limit 1;

    select value into v_secret
      from public.range_private_config
     where key='dynamic_flag_secret';

    if nullif(v_provider_session_id,'') is not null
       and nullif(v_provider_lab_key,'') is not null
       and nullif(v_secret,'') is not null then
      v_dynamic_flag := 'FORTIFY{' || substr(
        encode(hmac(
          v_provider_session_id || ':' || auth.uid()::text || ':' || v_provider_lab_key,
          v_secret,
          'sha256'
        ),'hex'),
        1,32
      ) || '}';
      v_valid := digest(btrim(coalesce(candidate_flag,'')),'sha256') = digest(v_dynamic_flag,'sha256');
    else
      v_valid := digest(btrim(coalesce(candidate_flag,'')),'sha256') = v_static_hash;
    end if;
  else
    v_valid := digest(btrim(coalesce(candidate_flag,'')),'sha256') = v_static_hash;
  end if;

  insert into public.ctf_flag_attempts(event_id,challenge_id,user_id,success)
  values(event_uuid,challenge_uuid,auth.uid(),v_valid);

  if not v_valid then return false; end if;

  insert into public.ctf_solves(event_id,challenge_id,user_id,points)
  values(event_uuid,challenge_uuid,auth.uid(),coalesce(v_event_points,0))
  on conflict(event_id,challenge_id,user_id) do nothing;
  get diagnostics v_inserted_event = row_count;

  if v_inserted_event=1 then
    insert into public.challenge_solves(user_id,challenge_id)
    values(auth.uid(),challenge_uuid)
    on conflict(user_id,challenge_id) do nothing;
    get diagnostics v_inserted_global = row_count;

    if v_inserted_global=1 then
      update public.profiles
         set xp=xp+coalesce(v_reward,0)
       where id=auth.uid();
    end if;
  end if;

  return true;
end;
$$;
revoke all on function public.submit_ctf_flag(uuid,uuid,text) from public;
grant execute on function public.submit_ctf_flag(uuid,uuid,text) to authenticated;

-- Existing leaderboard RPC signature is preserved. After freeze_at, solves made
-- after the freeze remain recorded but are hidden from non-admin scoreboard views
-- until the event is finished.
create or replace function public.get_ctf_leaderboard(event_uuid uuid, limit_count integer default 100)
returns table(user_id uuid,name text,headline text,points bigint,solves bigint,last_solve timestamptz)
language sql
stable
security definer
set search_path=public
as $$
  select p.id,p.name,p.headline,
         coalesce(sum(case
           when not public.is_admin()
            and e.status='live'
            and e.freeze_at is not null
            and now() >= e.freeze_at
            and s.solved_at > e.freeze_at then 0
           else s.points end),0)::bigint as points,
         count(case
           when not (
             not public.is_admin()
             and e.status='live'
             and e.freeze_at is not null
             and now() >= e.freeze_at
             and s.solved_at > e.freeze_at
           ) then s.id end)::bigint as solves,
         max(case
           when not (
             not public.is_admin()
             and e.status='live'
             and e.freeze_at is not null
             and now() >= e.freeze_at
             and s.solved_at > e.freeze_at
           ) then s.solved_at end) as last_solve
    from public.ctf_participants cp
    join public.ctf_events e on e.id=cp.event_id
    join public.profiles p on p.id=cp.user_id and not p.blocked
    left join public.ctf_solves s on s.event_id=cp.event_id and s.user_id=cp.user_id
   where cp.event_id=event_uuid
   group by p.id,p.name,p.headline,cp.joined_at,e.status,e.freeze_at
   order by points desc, solves desc, last_solve asc nulls last, cp.joined_at asc
   limit least(greatest(limit_count,1),200);
$$;
revoke all on function public.get_ctf_leaderboard(uuid,integer) from public;
grant execute on function public.get_ctf_leaderboard(uuid,integer) to authenticated;

-- ---------------------------------------------------------------------------
-- 2) Range limits / templates / audit. The actual hard capacity is also
--    enforced by range-provider-safe-v2, independent of the web application.
-- ---------------------------------------------------------------------------
create table if not exists public.range_plan_limits (
  code text primary key,
  max_concurrent_sessions integer not null check(max_concurrent_sessions between 0 and 50),
  max_ttl_minutes integer not null check(max_ttl_minutes between 15 and 720),
  monthly_minutes integer not null default 0 check(monthly_minutes >= 0),
  updated_at timestamptz not null default now()
);
insert into public.range_plan_limits(code,max_concurrent_sessions,max_ttl_minutes,monthly_minutes) values
  ('free',1,45,180),
  ('pro',1,120,6000),
  ('admin',10,240,0)
on conflict(code) do nothing;

create table if not exists public.lab_templates (
  id uuid primary key default gen_random_uuid(),
  provider_lab_id text not null unique,
  title text not null,
  provider text not null default 'gcp_vm',
  image_ref text,
  machine_type text,
  cpu numeric(5,2),
  memory_mb integer,
  disk_gb integer,
  default_ttl_minutes integer not null default 60 check(default_ttl_minutes between 15 and 720),
  estimated_cost_cents_per_hour integer not null default 0 check(estimated_cost_cents_per_hour >= 0),
  published boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.range_audit_log (
  id bigint generated by default as identity primary key,
  event_type text not null,
  user_id uuid references public.profiles(id) on delete set null,
  lab_id uuid references public.labs(id) on delete set null,
  provider_session_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists range_audit_recent_idx on public.range_audit_log(created_at desc);

-- ---------------------------------------------------------------------------
-- 3) Verified skills + badges generated by real Challenge solves.
-- ---------------------------------------------------------------------------
create table if not exists public.skills (
  code text primary key,
  name text not null,
  category text not null default 'Cybersecurity'
);
insert into public.skills(code,name,category) values
 ('web','Web Security','Offensive Security'),
 ('linux','Linux','Systems'),
 ('windows','Windows','Systems'),
 ('ad','Active Directory','Enterprise'),
 ('network','Network Security','Infrastructure'),
 ('forensics','Forensics','Blue Team'),
 ('reverse','Reverse Engineering','Binary'),
 ('pwn','Binary Exploitation','Binary'),
 ('crypto','Cryptography','Foundations')
on conflict(code) do nothing;

create table if not exists public.challenge_skills (
  challenge_id uuid not null references public.challenges(id) on delete cascade,
  skill_code text not null references public.skills(code) on delete cascade,
  weight integer not null default 1 check(weight between 1 and 10),
  primary key(challenge_id,skill_code)
);

create table if not exists public.user_skill_xp (
  user_id uuid not null references public.profiles(id) on delete cascade,
  skill_code text not null references public.skills(code) on delete cascade,
  xp integer not null default 0 check(xp >= 0),
  updated_at timestamptz not null default now(),
  primary key(user_id,skill_code)
);

create table if not exists public.badges (
  code text primary key,
  name text not null,
  description text not null,
  threshold_solves integer not null default 1 check(threshold_solves > 0)
);
insert into public.badges(code,name,description,threshold_solves) values
 ('first-pwn','Primeiro Pwn','Concluiu o primeiro Challenge verificado.',1),
 ('hunter-10','Hunter','Concluiu 10 Challenges verificados.',10),
 ('operator-25','Operator','Concluiu 25 Challenges verificados.',25),
 ('elite-50','Elite','Concluiu 50 Challenges verificados.',50)
on conflict(code) do update set
  name=excluded.name,
  description=excluded.description,
  threshold_solves=excluded.threshold_solves;

create table if not exists public.user_badges (
  user_id uuid not null references public.profiles(id) on delete cascade,
  badge_code text not null references public.badges(code) on delete cascade,
  awarded_at timestamptz not null default now(),
  primary key(user_id,badge_code)
);

create or replace function public.award_verified_skill_progress()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
declare
  v_reward integer;
  v_count integer;
begin
  select xp_reward into v_reward from public.challenges where id=new.challenge_id;

  insert into public.user_skill_xp(user_id,skill_code,xp,updated_at)
  select new.user_id,cs.skill_code,greatest(1,coalesce(v_reward,50) * cs.weight),now()
    from public.challenge_skills cs
   where cs.challenge_id=new.challenge_id
  on conflict(user_id,skill_code)
  do update set xp=public.user_skill_xp.xp+excluded.xp,updated_at=now();

  select count(*)::integer into v_count
    from public.challenge_solves where user_id=new.user_id;

  insert into public.user_badges(user_id,badge_code)
  select new.user_id,b.code from public.badges b where v_count >= b.threshold_solves
  on conflict(user_id,badge_code) do nothing;

  return new;
end;
$$;

drop trigger if exists challenge_solve_verified_progress on public.challenge_solves;
create trigger challenge_solve_verified_progress
after insert on public.challenge_solves
for each row execute procedure public.award_verified_skill_progress();

-- Rebuild skill totals from historical solves each time this migration is applied.
insert into public.user_skill_xp(user_id,skill_code,xp,updated_at)
select csov.user_id,
       cskill.skill_code,
       sum(greatest(1,coalesce(ch.xp_reward,50) * cskill.weight))::integer,
       now()
  from public.challenge_solves csov
  join public.challenges ch on ch.id=csov.challenge_id
  join public.challenge_skills cskill on cskill.challenge_id=csov.challenge_id
 group by csov.user_id,cskill.skill_code
on conflict(user_id,skill_code)
do update set xp=excluded.xp,updated_at=now();

insert into public.user_badges(user_id,badge_code)
select counts.user_id,b.code
from (
  select user_id,count(*)::integer as solves
  from public.challenge_solves
  group by user_id
) counts
join public.badges b on counts.solves >= b.threshold_solves
on conflict(user_id,badge_code) do nothing;

-- ---------------------------------------------------------------------------
-- 4) RLS / grants.
-- ---------------------------------------------------------------------------
alter table public.ctf_flag_attempts enable row level security;
alter table public.range_plan_limits enable row level security;
alter table public.lab_templates enable row level security;
alter table public.range_audit_log enable row level security;
alter table public.skills enable row level security;
alter table public.challenge_skills enable row level security;
alter table public.user_skill_xp enable row level security;
alter table public.badges enable row level security;
alter table public.user_badges enable row level security;

revoke all on public.ctf_flag_attempts from anon,authenticated;

-- Admin operational reads.
drop policy if exists range_plan_limits_admin_read on public.range_plan_limits;
create policy range_plan_limits_admin_read on public.range_plan_limits
for select to authenticated using (public.is_admin());

drop policy if exists lab_templates_admin_read on public.lab_templates;
create policy lab_templates_admin_read on public.lab_templates
for select to authenticated using (public.is_admin());

drop policy if exists range_audit_admin_read on public.range_audit_log;
create policy range_audit_admin_read on public.range_audit_log
for select to authenticated using (public.is_admin());

grant select on public.range_plan_limits,public.lab_templates,public.range_audit_log to authenticated;

-- Skills are visible to active users; progress is own-or-admin.
drop policy if exists skills_read on public.skills;
create policy skills_read on public.skills for select to authenticated
using (public.current_user_active());

drop policy if exists challenge_skills_read on public.challenge_skills;
create policy challenge_skills_read on public.challenge_skills for select to authenticated
using (public.current_user_active());

drop policy if exists badges_read on public.badges;
create policy badges_read on public.badges for select to authenticated
using (public.current_user_active());

drop policy if exists user_skill_xp_read on public.user_skill_xp;
create policy user_skill_xp_read on public.user_skill_xp for select to authenticated
using (user_id=auth.uid() or public.is_admin());

drop policy if exists user_badges_read on public.user_badges;
create policy user_badges_read on public.user_badges for select to authenticated
using (user_id=auth.uid() or public.is_admin());

grant select on public.skills,public.challenge_skills,public.user_skill_xp,public.badges,public.user_badges to authenticated;

notify pgrst, 'reload schema';
