import Link from 'next/link'
import { Activity, ArrowRight, Boxes, CheckCircle2, Flag, GraduationCap, RadioTower, Swords, Trophy, Zap } from 'lucide-react'
import { DashboardShell } from '@/components/DashboardShell'
import LogoutButton from '@/components/LogoutButton'
import { requireUser } from '@/lib/auth'

export default async function Painel(){
 const {supabase,user}=await requireUser()
 const [{data:profile},{data:enrollments},{data:progress},{data:solves},{data:sessions},{data:labs},{data:challenges},{data:events},{data:ranking}]=await Promise.all([
  supabase.from('profiles').select('name,role,xp,headline').eq('id',user.id).single(),
  supabase.from('enrollments').select('id,course_id,status,courses(title,slug,description)').eq('user_id',user.id).eq('status','active'),
  supabase.from('lesson_progress').select('lesson_id,completed,completed_at').eq('user_id',user.id).eq('completed',true).order('completed_at',{ascending:false}),
  supabase.from('challenge_solves').select('id,solved_at,challenge_id,challenges(title,xp_reward)').eq('user_id',user.id).order('solved_at',{ascending:false}).limit(5),
  supabase.from('lab_sessions').select('id,status,started_at,expires_at,lab_id,labs(title,slug)').eq('user_id',user.id).order('started_at',{ascending:false}).limit(5),
  supabase.from('labs').select('id,title,slug,difficulty,estimated_minutes').eq('published',true).limit(4),
  supabase.from('challenges').select('id,title,slug,category,difficulty,xp_reward').eq('published',true).limit(4),
  supabase.from('ctf_events').select('id,title,starts_at,ends_at,prize_text,status').in('status',['scheduled','live']).order('starts_at').limit(2),
  supabase.rpc('get_leaderboard',{limit_count:100})
 ])
 const courseIds=(enrollments||[]).map((e:any)=>e.course_id);const {data:courseLessons}=courseIds.length?await supabase.from('lessons').select('id,course_id').in('course_id',courseIds):{data:[] as any[]};const completed=new Set((progress||[]).map((p:any)=>p.lesson_id));const totalLessons=courseLessons?.length||0;const pct=totalLessons?Math.round(completed.size/totalLessons*100):0;const running=((sessions||[]).find((s:any)=>s.status==='running')||null) as any;const rank=(ranking||[]).findIndex((r:any)=>r.id===user.id)+1;const liveCtf=(events||[]).find((e:any)=>e.status==='live')||(events||[])[0]
 return <DashboardShell admin={profile?.role==='admin'}>
  <div className="page-head command-head"><div><div className="kicker">OPERATOR / COMMAND CENTER</div><h1>Bem-vindo ao range, {profile?.name||user.email}</h1><p>{profile?.headline||'Continue sua formação, entre no range e acumule experiência prática.'}</p></div><div className="hero-actions">{profile?.role==='admin'&&<Link className="btn secondary" href="/admin">OPERATIONS CONSOLE</Link>}<LogoutButton/></div></div>
  <section className="operator-command-banner"><div className="command-progress"><div><span className="section-index">FORMAÇÃO ATUAL</span><strong>{pct}%</strong><small>{completed.size} de {totalLessons} aulas concluídas</small></div><div className="progress"><span style={{width:`${pct}%`}}/></div></div><div className="command-next">{running?<><span className="status-orb online"/><div><small>LAB EM EXECUÇÃO</small><strong>{running.labs?.title}</strong></div><Link className="btn" href={`/painel/labs/${running.labs?.slug}`}>RETOMAR LAB →</Link></>:enrollments?.length?<><GraduationCap size={22}/><div><small>PRÓXIMA AÇÃO</small><strong>Continue sua formação</strong></div><Link className="btn" href="/painel/cursos">ABRIR ACADEMY →</Link></>:<><GraduationCap size={22}/><div><small>COMECE AQUI</small><strong>Escolha sua formação</strong></div><Link className="btn" href="/painel/cursos">VER CURSOS →</Link></>}</div></section>
  <div className="dashboard-grid command-stats"><div className="stat-card accent"><Zap size={18}/><small>XP TOTAL</small><div className="stat">{profile?.xp||0}</div></div><div className="stat-card"><Trophy size={18}/><small>RANK GLOBAL</small><div className="stat">{rank>0?`#${rank}`:'—'}</div></div><div className="stat-card"><CheckCircle2 size={18}/><small>AULAS</small><div className="stat">{completed.size}</div></div><div className="stat-card"><Swords size={18}/><small>CHALLENGES</small><div className="stat">{solves?.length||0}</div></div></div>
  <section className="command-grid"><article className="card command-panel"><div className="panel-head"><div><span className="section-index">ACADEMY</span><h2>Minha formação</h2></div><Link className="tag green" href="/painel/cursos">TODOS →</Link></div>{enrollments?.length?<div className="command-course-list">{enrollments.slice(0,3).map((e:any)=><Link href={`/curso/${e.courses?.slug}`} className="command-course" key={e.id}><div className="activity-icon"><GraduationCap size={17}/></div><div><strong>{e.courses?.title}</strong><span>{e.courses?.description||'Continuar formação'}</span></div><ArrowRight size={16}/></Link>)}</div>:<div className="empty-state">Sua formação aparecerá aqui quando você escolher um curso.</div>}</article>
   <article className="card command-panel"><div className="panel-head"><div><span className="section-index">CYBER RANGE</span><h2>Labs disponíveis</h2></div><Link className="tag green" href="/painel/labs">RANGE →</Link></div><div className="command-mini-grid">{(labs||[]).slice(0,4).map((l:any)=><Link href={`/painel/labs/${l.slug}`} className="command-mini-card" key={l.id}><Boxes size={17}/><div><strong>{l.title}</strong><span>{l.difficulty} · {l.estimated_minutes} min</span></div></Link>)}{!labs?.length&&<div className="empty-inline">Nenhum Lab publicado.</div>}</div></article>
   <article className="card command-panel"><div className="panel-head"><div><span className="section-index">MISSIONS</span><h2>Challenges</h2></div><Link className="tag green" href="/painel/desafios">TODOS →</Link></div><div className="command-mini-grid">{(challenges||[]).slice(0,4).map((c:any)=><Link href={`/painel/desafios/${c.slug}`} className="command-mini-card" key={c.id}><Swords size={17}/><div><strong>{c.title}</strong><span>{c.category} · {c.difficulty} · +{c.xp_reward} XP</span></div></Link>)}{!challenges?.length&&<div className="empty-inline">Nenhum Challenge publicado.</div>}</div></article>
   <article className="card command-panel ctf-command-panel"><div className="panel-head"><div><span className="section-index">COMPETE</span><h2>CTF</h2></div><RadioTower size={18}/></div>{liveCtf?<><span className={`pill ${liveCtf.status==='live'?'active':''}`}>{liveCtf.status==='live'?'AO VIVO':'PRÓXIMO EVENTO'}</span><h3>{liveCtf.title}</h3><div className="meta-row"><span>{new Date(liveCtf.starts_at).toLocaleString('pt-BR')}</span><span>{liveCtf.prize_text||'PRÊMIO A DEFINIR'}</span></div><Link className="btn secondary" href="/painel/ctf"><Flag size={15}/> ABRIR CTF →</Link></>:<div className="empty-state">Nenhum evento anunciado.</div>}</article>
  </section>
  <section className="card activity-console"><div className="panel-head"><div><span className="section-index">ACTIVITY FEED</span><h3>Atividade recente</h3></div><Activity size={18}/></div><div className="activity-list">{(solves||[]).map((s:any)=><div className="activity-row" key={s.id}><div className="activity-icon"><Trophy size={16}/></div><div><strong>{s.challenges?.title}</strong><span>Challenge resolvido</span></div><span className="xp-score">+{s.challenges?.xp_reward||0} XP</span></div>)}{(sessions||[]).slice(0,3).map((s:any)=><div className="activity-row" key={s.id}><div className="activity-icon"><Boxes size={16}/></div><div><strong>{s.labs?.title}</strong><span>Sessão {s.status}</span></div><span className="mono">LAB</span></div>)}{!solves?.length&&!sessions?.length&&<div className="empty-state">Sua atividade aparecerá aqui conforme você usa a plataforma.</div>}</div></section>
 </DashboardShell>
}
