import { notFound, redirect } from 'next/navigation'
import { CheckCircle2, Download, ExternalLink, Flag, Network, Power, ShieldCheck, Swords, TerminalSquare } from 'lucide-react'
import { DifficultyMeter } from '@/components/ui/DifficultyMeter'
import { SubmitButton } from '@/components/ui/SubmitButton'
import { requireUser } from '@/lib/auth'
import { startChallengeTargetAction, stopChallengeTargetAction, submitChallengeAction } from '@/app/actions'
import { getPlatformAccess } from '@/lib/platform-access'
import { createAdminClient } from '@/lib/supabase/admin'

export default async function ChallengePage({params,searchParams}:{params:Promise<{slug:string}>,searchParams:Promise<{result?:string,ctf?:string}>}){
 const {slug}=await params;const query=await searchParams;const {user,supabase}=await requireUser();const eventId=String(query.ctf||'')
 const access=await getPlatformAccess(user.id)
 if(!access.canAccessCyberRange)redirect('/painel/desafios')
 const {data:c}=await supabase.from('challenges').select('id,title,slug,description,category,difficulty,xp_reward,briefing,lab_id').eq('slug',slug).eq('published',true).maybeSingle()
 if(!c)notFound()
 const admin=createAdminClient()
 const [{data:solve},{data:lab},{data:session},{data:eventLink}]=await Promise.all([
  supabase.from('challenge_solves').select('id,solved_at').eq('user_id',user.id).eq('challenge_id',c.id).maybeSingle(),
  c.lab_id?admin.from('labs').select('id,title,estimated_minutes,published').eq('id',c.lab_id).maybeSingle():Promise.resolve({data:null} as any),
  c.lab_id?admin.from('lab_sessions').select('id,status,started_at,expires_at,target_address,vpn_download_url,connection_url').eq('user_id',user.id).eq('lab_id',c.lab_id).eq('status','running').gt('expires_at',new Date().toISOString()).order('started_at',{ascending:false}).limit(1).maybeSingle():Promise.resolve({data:null} as any),
  eventId?admin.from('ctf_event_challenges').select('event_id,challenge_id,ctf_events(id,title,status,starts_at,ends_at)').eq('event_id',eventId).eq('challenge_id',c.id).maybeSingle():Promise.resolve({data:null} as any)
 ])
 if(eventId&&!eventLink)redirect('/painel/ctf')
 const event=Array.isArray((eventLink as any)?.ctf_events)?(eventLink as any).ctf_events[0]:(eventLink as any)?.ctf_events
 const activeCtf=Boolean(eventId&&event)
 const ctfLive=Boolean(activeCtf&&event?.status==='live'&&Date.now()>=new Date(event.starts_at).getTime()&&Date.now()<=new Date(event.ends_at).getTime())
 return <>
   <div className="challenge-workspace-head"><div><div className="kicker">{activeCtf?`CTF / ${String(event?.title||'EVENTO').toUpperCase()}`:`MISSION / ${c.category.toUpperCase()}`}</div><h1>{c.title}</h1><p>{c.description}</p></div><div className="mission-score"><span>{activeCtf?'CTF REWARD':'REWARD'}</span><strong>+{c.xp_reward} XP</strong></div></div>
   <div className="mission-meta-bar"><DifficultyMeter difficulty={c.difficulty}/><span className="mission-divider"/><span className="mono"><Swords size={13}/> {c.category.toUpperCase()}</span><span className="mission-divider"/><span className={`mono ${solve?'terminal-green':''}`}>{solve?'PWNED':'UNSOLVED'}</span>{activeCtf&&<><span className="mission-divider"/><a className="mono" href={`/painel/ctf/${eventId}`}>VOLTAR AO CTF</a></>}</div>
   {query.result==='invalid'&&<div className="alert danger-alert">Flag inválida ou CTF indisponível. Revise a exploração e tente novamente.</div>}
   {query.result==='provider'&&<div className="alert danger-alert">Não foi possível provisionar o alvo. Verifique o Range Provider.</div>}
   {query.result==='solved'&&<div className="alert success-alert"><CheckCircle2 size={16}/> Flag correta. {activeCtf?'Pontuação do evento registrada.':'XP creditado no seu perfil.'}</div>}
   <div className="challenge-workspace-grid"><section>
     <div className="card mission-briefing"><div className="panel-head"><div><span className="section-index">01 / BRIEFING</span><h3>Objetivo da missão</h3></div><Flag size={19}/></div><p className="muted briefing-text" style={{whiteSpace:'pre-wrap'}}>{c.briefing||'Analise o cenário e encontre a flag dentro do escopo proposto. Use somente os ativos disponibilizados pela FortifySec.'}</p><div className="scope-box"><ShieldCheck size={17}/><div><strong>Escopo autorizado</strong><span>Somente ambiente disponibilizado neste Challenge.</span></div></div></div>
     {lab&&(!activeCtf||ctfLive)&&<div className="card" style={{marginTop:18}}><div className="panel-head"><div><span className="section-index">02 / TARGET</span><h3>Alvo isolado</h3></div><Network size={19}/></div>{session?<><div className="target-row"><span>STATUS</span><strong className="terminal-green">RUNNING</strong></div><div className="target-row"><span>TARGET</span><strong>{session.target_address||'Aguardando endereço'}</strong></div><div className="target-row"><span>EXPIRA</span><strong>{session.expires_at?new Date(session.expires_at).toLocaleString('pt-BR'):'—'}</strong></div><div className="hero-actions" style={{marginTop:16}}>{session.target_address?.startsWith('http')&&<a className="btn" href={session.target_address} target="_blank" rel="noreferrer"><ExternalLink size={15}/> ABRIR TARGET</a>}{session.vpn_download_url&&<a className="btn secondary" href={session.vpn_download_url}><Download size={15}/> BAIXAR VPN</a>}<form action={stopChallengeTargetAction}><input type="hidden" name="lab_id" value={c.lab_id||''}/><input type="hidden" name="slug" value={c.slug}/>{activeCtf&&<input type="hidden" name="ctf_event_id" value={eventId}/>}<SubmitButton className="btn danger" idleLabel="ENCERRAR ALVO" pendingLabel="ENCERRANDO..."/></form></div></>:<><p className="muted">Inicie o alvo para criar um ambiente isolado exclusivo da sua sessão.</p><form action={startChallengeTargetAction}><input type="hidden" name="challenge_id" value={c.id}/><input type="hidden" name="slug" value={c.slug}/>{activeCtf&&<input type="hidden" name="ctf_event_id" value={eventId}/>}<SubmitButton className="btn full-btn" idleLabel="INICIAR ALVO →" pendingLabel="PROVISIONANDO..."/></form></>}<div className="security-note"><Power size={14}/><span>{session?.vpn_download_url?'A VPN recebe rota apenas para o alvo privado desta sessão.':'O método de acesso é definido pelo provider do Cyber Range.'}</span></div></div>}
     {lab&&activeCtf&&!ctfLive&&<div className="card" style={{marginTop:18}}><div className="panel-head"><div><span className="section-index">02 / TARGET</span><h3>Alvo bloqueado</h3></div><Network size={19}/></div><p className="muted">O alvo será liberado quando o CTF estiver ao vivo.</p></div>}
   </section><aside className="card flag-terminal"><div className="terminal-toolbar"><span><TerminalSquare size={15}/> FLAG SUBMISSION</span><span className={`pill ${solve?'active':''}`}>{solve?'VERIFIED':'AWAITING FLAG'}</span></div>{activeCtf&&!ctfLive?<div className="pwned-state"><Flag size={38}/><strong>CTF BLOQUEADO</strong><p>A submissão será liberada quando o evento estiver ao vivo.</p></div>:solve&&!activeCtf?<div className="pwned-state"><CheckCircle2 size={38}/><strong>CHALLENGE PWNED</strong><p>Resolvido em {solve.solved_at?new Date(solve.solved_at).toLocaleString('pt-BR'):'sessão anterior'}.</p><small>O XP desta missão já foi contabilizado.</small></div>:<><div className="terminal-instructions"><span className="terminal-green">fortify@challenge</span>:~$ submit --flag</div><form action={submitChallengeAction} className="flag-submit-form"><input type="hidden" name="challenge_id" value={c.id}/><input type="hidden" name="slug" value={c.slug}/>{activeCtf&&<input type="hidden" name="ctf_event_id" value={eventId}/>}<div className="field"><label>FLAG</label><input required name="flag" autoComplete="off" spellCheck={false} placeholder="FORTIFY{...}"/></div><SubmitButton className="btn full-btn" idleLabel="ENVIAR FLAG →" pendingLabel="VALIDANDO FLAG..."/></form><p className="security-copy">{activeCtf?'A flag vale pontos dentro deste evento.':'Envie a flag encontrada para concluir a missão e registrar sua pontuação.'}</p></>}</aside></div>
 </>
}
