import Link from 'next/link'
import { notFound } from 'next/navigation'
import { addAssetAction, addOrganizationMemberAction, createIncidentAction, createMonthlyReportAction, deleteTrialPlaceholderOrganizationAction, recordRecoveryTestAction, resolveIncidentAction, setOrganizationStatusAction } from '@/app/admin/actions'
import { PortalHeader } from '@/components/PortalHeader'
import { StatusPill } from '@/components/StatusPill'
import { getAdminClientDetail } from '@/lib/admin-data'

export default async function ClientDetail({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<Record<string, string | undefined>> }) {
  const { id } = await params
  const q = await searchParams
  const data = await getAdminClientDetail(id)
  if (!data) notFound()
  const { org, assets, incidents, recovery, backups, members, reports, tickets } = data
  return <><PortalHeader kicker="ADMIN / CLIENT OPS" title={org.name} copy={`Plano ${org.plan} · ${org.data_volume || 'volume não informado'} · RPO ${org.rpo_target || '—'} · RTO ${org.rto_target || '—'}`} action={<StatusPill tone={org.status === 'active' ? 'green' : org.status === 'suspended' ? 'danger' : 'cyan'}>{org.status}</StatusPill>}/>{Object.keys(q).some((key) => key !== 'error') && <div className="form-success">Operação concluída e painel atualizado.</div>}{q.error && <div className="form-error">Não foi possível concluir: {q.error}.</div>}

    {org.provider === 'acronis' && <section className="portal-card" style={{marginBottom:12}}><div className="card-head"><div><span className="section-index">PROVIDER INTEGRATION</span><h2>Acronis Cyber Protect Cloud</h2></div><StatusPill tone="green">MAPEADO</StatusPill></div><div className="admin-line"><strong>Tenant Acronis</strong><span>{org.provider_tenant_id || '—'}</span></div><div className="admin-line"><strong>Último sync</strong><span>{org.last_provider_sync_at ? new Date(org.last_provider_sync_at).toLocaleString('pt-BR') : 'Ainda não sincronizado'}</span></div><p style={{marginTop:12}}>O tenant Acronis é o ambiente técnico. Esta organização é o cadastro comercial/operacional da Fortify. Acesso ao portal é controlado separadamente em “Usuários vinculados”.</p></section>}

    <section className="portal-card admin-org-control"><div><span className="section-index">ORGANIZATION STATUS</span><h2>Estado do ambiente</h2><p>Use “ativo” quando políticas, ativos e integração inicial estiverem prontos.</p><code className="org-id">ORG_ID: {org.id}</code></div><form action={setOrganizationStatusAction}><input type="hidden" name="organization_id" value={org.id}/><select name="status" defaultValue={org.status}><option value="onboarding">Onboarding</option><option value="active">Ativo</option><option value="suspended">Suspenso</option></select><button className="btn" type="submit">ATUALIZAR</button></form></section>

    {String(org.name).trim().toLowerCase() === 'my first customer' && !org.provider_tenant_id && <section className="portal-card" style={{marginBottom:12,borderColor:'rgba(255,200,87,.3)'}}><div className="card-head"><div><span className="section-index">TRIAL PLACEHOLDER</span><h2>Organização criada a partir do tenant padrão da Acronis</h2></div><StatusPill tone="warning">LIMPEZA</StatusPill></div><p>Se este cadastro foi criado por engano e não possui ativos, backups, incidentes, testes, relatórios ou chamados, ele pode ser removido com segurança.</p><form action={deleteTrialPlaceholderOrganizationAction}><input type="hidden" name="organization_id" value={org.id}/><button className="btn secondary" type="submit">EXCLUIR “MY FIRST CUSTOMER” VAZIO</button></form></section>}

    <section className="admin-ops-grid">
      <form className="portal-card compact-form" action={addAssetAction}><span className="section-index">PROTECTED ASSET</span><h2>Adicionar ativo</h2><input type="hidden" name="organization_id" value={org.id}/><label>Nome<input name="name" required placeholder="ERP-PROD / FILESERVER-01"/></label><div className="form-row"><label>Tipo<select name="asset_type"><option>server</option><option>database</option><option>filesystem</option><option>microsoft-365</option><option>vm</option><option>workload</option></select></label><label>Status<select name="status"><option value="pending">Pendente</option><option value="protected">Protegido</option><option value="warning">Atenção</option></select></label></div><label>Área<input name="owner_area" placeholder="TI / Financeiro"/></label><label>Política<input name="policy_name" placeholder="Business-4H-30D"/></label><label>Bytes protegidos<input type="number" min="0" name="protected_bytes" defaultValue="0"/></label><button className="btn full" type="submit">SALVAR ATIVO</button></form>

      <form className="portal-card compact-form" action={recordRecoveryTestAction}><span className="section-index">RECOVERY TEST</span><h2>Registrar teste</h2><input type="hidden" name="organization_id" value={org.id}/><label>Ativo<select name="asset_id" defaultValue=""><option value="">Geral / não vinculado</option>{assets.map((a: any) => <option value={a.id} key={a.id}>{a.name}</option>)}</select></label><label>Tipo<input name="test_type" defaultValue="File restore"/></label><div className="form-row"><label>Resultado<select name="status"><option value="passed">Aprovado</option><option value="failed">Falhou</option><option value="planned">Planejado</option></select></label><label>RTO em segundos<input type="number" min="0" name="rto_seconds"/></label></div><label>Notas<textarea name="notes" rows={3}/></label><button className="btn full" type="submit">REGISTRAR TESTE</button></form>

      <form className="portal-card compact-form" action={createIncidentAction}><span className="section-index">INCIDENT</span><h2>Abrir incidente</h2><input type="hidden" name="organization_id" value={org.id}/><label>Título<input name="title" required placeholder="Falha de backup / comportamento anômalo"/></label><label>Severidade<select name="severity"><option value="low">Baixa</option><option value="medium">Média</option><option value="high">Alta</option><option value="critical">Crítica</option></select></label><label>Resumo<textarea name="summary" rows={4}/></label><button className="btn full" type="submit">ABRIR INCIDENTE</button></form>

      <form className="portal-card compact-form" action={addOrganizationMemberAction}><span className="section-index">ACCESS / RBAC</span><h2>Vincular usuário</h2><input type="hidden" name="organization_id" value={org.id}/><label>E-mail da conta<input type="email" name="email" required placeholder="usuario@empresa.com.br"/></label><label>Perfil<select name="member_role"><option value="viewer">Visualização</option><option value="operator">Operador</option><option value="admin">Administrador</option></select></label><button className="btn full" type="submit">VINCULAR CONTA</button><small>O usuário precisa ter criado uma conta Fortify Cloud antes de ser vinculado.</small></form>

      <form className="portal-card compact-form" action={createMonthlyReportAction}><span className="section-index">MONTHLY REPORT</span><h2>Publicar relatório</h2><input type="hidden" name="organization_id" value={org.id}/><label>Mês<input type="month" name="reference_month" required/></label><div className="form-row"><label>Health score %<input type="number" min="0" max="100" step="0.1" name="health_score"/></label><label>Backup success %<input type="number" min="0" max="100" step="0.1" name="backup_success_rate"/></label></div><div className="form-row"><label>Recovery tests aprovados<input type="number" min="0" name="recovery_tests_passed"/></label><label>Incidentes<input type="number" min="0" name="incidents_count"/></label></div><label>URL do relatório<input type="url" name="report_url" placeholder="https://.../relatorio.pdf"/></label><button className="btn full" type="submit">PUBLICAR RELATÓRIO</button></form>
    </section>

    <section className="portal-card"><div className="card-head"><div><span className="section-index">ASSETS</span><h2>Ativos protegidos</h2></div><StatusPill tone="cyan">{assets.length} ATIVOS</StatusPill></div><div className="data-table team-table"><div className="table-row head"><span>Nome</span><span>Tipo</span><span>Política</span><span>Status</span></div>{assets.map((a: any) => <div className="table-row" key={a.id}><strong>{a.name}</strong><span>{a.asset_type}</span><span>{a.policy_name || '—'}</span><StatusPill tone={a.status === 'protected' ? 'green' : a.status === 'warning' ? 'warning' : 'cyan'}>{a.status}</StatusPill></div>)}</div></section>

    <section className="admin-detail-grid"><article className="portal-card"><div className="card-head"><h2>Backups recentes</h2><StatusPill>{backups.length}</StatusPill></div>{backups.length ? backups.slice(0, 8).map((b: any) => <div className="admin-line" key={b.id}><strong>{b.cloud_protected_assets?.name || 'Ativo'}</strong><span>{b.provider || 'provider'} · {b.status}</span></div>) : <p>Nenhum evento de backup recebido.</p>}</article><article className="portal-card"><div className="card-head"><h2>Recovery tests</h2><StatusPill tone="cyan">{recovery.length}</StatusPill></div>{recovery.length ? recovery.slice(0, 8).map((r: any) => <div className="admin-line" key={r.id}><strong>{r.cloud_protected_assets?.name || r.test_type}</strong><span>{r.status} · {r.rto_seconds ? `${r.rto_seconds}s` : 'RTO —'}</span></div>) : <p>Nenhum teste registrado.</p>}</article></section>

    <section className="portal-card"><div className="card-head"><h2>Incidentes</h2><StatusPill tone={incidents.some((i: any) => i.status !== 'resolved') ? 'warning' : 'green'}>{incidents.filter((i: any) => i.status !== 'resolved').length} ABERTOS</StatusPill></div>{incidents.length ? incidents.map((i: any) => <div className="incident-admin-row" key={i.id}><div><StatusPill tone={i.severity === 'critical' ? 'danger' : i.severity === 'high' ? 'warning' : 'cyan'}>{i.severity}</StatusPill><strong>{i.title}</strong><span>{i.summary || 'Sem resumo'} · {i.status}</span></div>{i.status !== 'resolved' && <form action={resolveIncidentAction}><input type="hidden" name="organization_id" value={org.id}/><input type="hidden" name="incident_id" value={i.id}/><button className="btn secondary" type="submit">RESOLVER</button></form>}</div>) : <p>Nenhum incidente registrado.</p>}</section>

    <section className="portal-card"><div className="card-head"><h2>Usuários vinculados</h2><StatusPill tone="cyan">{members.length}</StatusPill></div><div className="data-table team-table"><div className="table-row head"><span>E-mail</span><span>Perfil</span><span>Status</span><span>Organização</span></div>{members.map((m: any) => <div className="table-row" key={m.user_id}><strong>{m.email}</strong><span>{m.member_role}</span><StatusPill>ATIVO</StatusPill><span>{org.name}</span></div>)}</div></section>

    <section className="admin-detail-grid"><article className="portal-card"><div className="card-head"><h2>Relatórios</h2><StatusPill tone="cyan">{reports.length}</StatusPill></div>{reports.length ? reports.map((r: any) => <div className="admin-line" key={r.id}><div><strong>{new Date(`${r.reference_month}T12:00:00`).toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</strong><small className="table-subtext">{r.source==='client'?'gerado pelo cliente':'Fortify Ops'} · {r.health_score || 0}% health</small></div><Link className="text-link" href={`/admin/relatorios/${r.id}`}>ABRIR →</Link></div>) : <p>Nenhum relatório mensal gerado.</p>}</article><article className="portal-card"><div className="card-head"><h2>Chamados de suporte</h2><StatusPill tone={tickets.some((t: any) => !['resolved','closed'].includes(t.status)) ? 'warning' : 'green'}>{tickets.filter((t: any) => !['resolved','closed'].includes(t.status)).length} ATIVOS</StatusPill></div>{tickets.length ? tickets.map((t: any) => <div className="incident-admin-row" key={t.id}><div><StatusPill tone={t.priority === 'critical' ? 'danger' : t.priority === 'high' ? 'warning' : 'cyan'}>{t.priority}</StatusPill><strong>{t.subject}</strong><span>{String(t.status).replaceAll('_',' ')} · atualizado {new Date(t.updated_at??t.created_at).toLocaleString('pt-BR')}</span></div><Link className="btn secondary" href={`/admin/chamados/${t.id}`}>OPERAR</Link></div>) : <p>Nenhum chamado registrado.</p>}</article></section>
  </>
}
