import { BriefcaseBusiness } from 'lucide-react'
import { CompanyShell } from '@/components/CompanyShell'
import { requireCompany } from '@/lib/auth'
import { companyCreateJobAction } from '@/app/actions'
import { SubmitButton } from '@/components/ui/SubmitButton'

export default async function NewJob({searchParams}:{searchParams:Promise<{erro?:string}>}){
 const q=await searchParams;const {company}=await requireCompany()
 return <CompanyShell companyName={company.name}><div className="page-head internal-page-head"><div><div className="kicker">EMPLOYER / NEW JOB</div><h1>Publicar vaga</h1><p>Crie uma oportunidade para os talentos da FortifySec.</p></div><BriefcaseBusiness size={26}/></div>{q.erro&&<div className="alert danger-alert">{q.erro}</div>}<form action={companyCreateJobAction} className="card content-studio"><div className="two-col"><div className="field"><label>Título</label><input name="title" required placeholder="Analista de Segurança Jr."/></div><div className="field"><label>Senioridade</label><input name="seniority" placeholder="Júnior / Pleno / Sênior"/></div><div className="field"><label>Modelo</label><select name="work_mode"><option value="remote">Remoto</option><option value="hybrid">Híbrido</option><option value="onsite">Presencial</option></select></div><div className="field"><label>Contrato</label><select name="employment_type"><option value="full_time">Tempo integral</option><option value="part_time">Meio período</option><option value="contract">Contrato / PJ</option><option value="internship">Estágio</option></select></div><div className="field"><label>Localização</label><input name="location" placeholder="São Paulo, SP / Brasil"/></div><div className="field"><label>Publicação</label><select name="status"><option value="published">Publicar agora</option><option value="draft">Salvar rascunho</option></select></div><div className="field"><label>Salário mínimo (R$)</label><input name="salary_min" type="number" min="0"/></div><div className="field"><label>Salário máximo (R$)</label><input name="salary_max" type="number" min="0"/></div></div><div className="field"><label>Descrição</label><textarea name="description" rows={7} required/></div><div className="field"><label>Requisitos</label><textarea name="requirements" rows={7}/></div><SubmitButton idleLabel="PUBLICAR VAGA →" pendingLabel="PUBLICANDO..."/></form></CompanyShell>
}
